### ISSUE TITLE
Problem when manually editing nginx.conf and then by vesta

### ISSUE THREAD

**Issue by emtudo** [serghey-rodin/vesta#1051]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql, postgress

### Steps to Reproduce:

Type here, e.g. install vesta and type rm -rf / --no-preserve-root

### Other Notes:

I believe that splitting configuration files by domain can lessen the failure that exists in configuration changes.

Because sometimes when you manually edit a configuration, and then for some reason enter the vesta and edit the settings there, it gets a garbage in the configuration files, so if you split these files one for each domain can eliminate this.

It would also be interesting to think of the same problem, to enable an option to insert a configuration file at the beginning and at the end, just as the "forge" tool does, besides allowing to edit the settings manually in the panel itself.

**Comment by nurul-umbhiya** [comment]
I agree. I've faced same problem yesterday. I'd to destroy my entire digital ocean droplet for this.

**Comment by emtudo** [comment]
Eu tenho esse mesmo problema, para evitar isso, eu criei um modelo novo /usr/local/vesta/dados/templates/web/nginx/ e criei um modelo que apenas inclui um arquivo PATH/$domain/custom.conf;

Assim eu faço como analisar, só tenho o trabalho de semper criar este arquivo.

**Comment by n1trux** [comment]
I think there should also be an option to set no automatic configuration at all (not "no-php" but really only the server directive) so you can have a completely custom config.

The problem we face currently is that the system isn't very stable when there are manual changes in the user's conf/web/nginx.conf files, so in my opinion we should eliminate the need to do so at all and only "allow" (=support) editing the `conf/web/nginx.sitename.conf`.

That could probably be done by moving the nginx.conf file into the `/etc/nginx/(vesta/)` directory and making it read-only for the user but writable by the vesta scripts.

For now it's also really, really easy for users to add other domains they don't own to their nginx.conf, which is a huge security hole and could be exploited by malicious users. VestaCP is not suitable for hosting a larger base of customers or unknown customers due to this at the moment.

**Comment by dpeca** [comment]
Both apache2.conf and nginx.conf (in /home/user/conf/web/) are writeable only for root.

**Comment by n1trux** [comment]
ah, right! Maybe that was my fault by trying out my own dev branch :/

Can we move them to `/etc/nginx/` or similar? It might be a bit confusing for users to see them in their directory.
