### ISSUE TITLE
Trying to access a user's domain via SSL if it's not enabled redirects to another user

### ISSUE THREAD

**Issue by n1trux** [serghey-rodin/vesta#1093]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

0.9.17

### Installed Software (what you got with the installer):

php-fpm, nginx, …

### Steps to Reproduce:

Have one user (`user1`) with an SSL enabled domain (`user1.example.com`) and the other (`user2`) without SSL (`user2.example.com`).

If you type in `http://user2.example.com` the correct files from `/home/user2/web/user2.example.com/public_html` get served, but if you type in `https://user2.example.com` the files from `/home/user1/web/user1.example.com/public_html` appear after you get an error that the certificate is not valid for user2.com as it's issued for user1.com (obviously).

### Other Notes:

This might be remedied by having domains which don't have SSL enabled in the web interface getting a redirect from the `https://` to non-https domain.

**Comment by Skamasle** [comment]
This isnt a bug.

This happen in cpanel, this happen also in plesk, this happen also if you not have any panel installed and just setup apache or nginx vhost

Why you get this "error"/"redirect" ?

You not have dedicated IPs in your domain.
As actually browsers support SNI you get this problems ( SNI https://en.wikipedia.org/wiki/Server_Name_Indication )

As you have one site whit ssl and orther one whitout if you try force SSL in domain whitout ssl it looking for something in por 443 to server you.

Also you can have orther problems whit sni, if you use windows xp and old browser and you can two sites whit SSL you maybe cant see any site because you not have dedicated IP and your browser not support SNI

Solution to this:

1- Add Dedicated IP to site whit ssl
2- Add SSL to all sites if you not have dedicated IPs
3- Try Add SSL a domain whit white page or message say something like " you see this because your ssl not have SSL"

**Comment by SnAFKe** [comment]
You can easily solve this forcing https to http

server {
        listen 443;
        server_name user2.example.com;
       	return 301 http://$host$request_uri;	
}`

**Comment by n1trux** [comment]
The solution by @SnAFKe should be standard for non-SSL domains, in my opinion.
