### ISSUE TITLE
Problem with installing vesta on CentOS 7

### ISSUE THREAD

**Issue by 42p** [serghey-rodin/vesta#1231]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

latest

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql, fail2ban, quota etc..

### Steps to Reproduce:

`bash vst-install.sh --nginx yes --phpfpm yes --apache no --named yes --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav no --mysql yes --postgresql no`

```
sed: can't read /usr/lib/systemd/system/fail2ban.service: No such file or direct                                     ory
vst-install-rhel.sh: line 1207: systemctl: command not found
Starting fail2ban:                                         [  OK  ]
Stopping crond:                                            [  OK  ]
Starting crond:                                            [  OK  ]
quotaon: cannot find //aquota.group on /dev/vda1 [/]
quotaon: cannot find //aquota.user on /dev/vda1 [/]
Error: quota can't be enabled in /
Starting vesta-nginx:                                      [  OK  ]
Starting vesta-php:                                        [  OK  ]

```

**Comment by jstacklin** [comment]
Try to re-install your OS, and then run the command without the quota take (--quota no) and I personally haven't had this issue.

**Comment by chipitsine** [comment]
it seems that you are asking vesta to use quota while quota is not enabled.

what should be a proper behaviour ? stop installing ? ignore quota ?

**Comment by jodumont** [comment]
I hope I don't hijack the subject but for me it point to the same kind of issue

I installed VestaCP on CentOS7 with quota and on reboot I had to comment these options on /home
`#,usrquota,grpquota,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0`

Of course it was a plain minimal CentOS and I never install quota by my own because I tough VestaCP script will take care of it.

So my question is; it is a missing part in the VestaCP script, or we need to setup manually the quota ?
