### ISSUE TITLE
Upgrade MySQL from 5.7 to 8.0

### ISSUE THREAD

**Issue by skyhigh119** [serghey-rodin/vesta#1714]
### Operating System (OS/VERSION):
Ubuntu  18.04

### VestaCP Version:
0.9.8-22

### Installed Software (what you got with the installer):
apache+nginx ,;
vsftpd ;
exim + dovecot + spamassassin + clamav ;
mysql 5.7

### Steps to Reproduce:
1. wget mysql-apt-config_0.8.10-1_all.deb form (https://dev.mysql.com/downloads/repo/apt/)
2. sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
3. config apt configuration
4. sudo apt-get install mysql-server

### Related Issues/Forum Threads:
I cant find clue from anything for that.

### Other Notes:

I'am newbie in server, so sorrry if u dont know what i said, but my trouble is can't update mysql from 5.7 to 8 series.

**Comment by Skamasle** [comment]
Vesta not support mysql 8 yet.

We do support to 5.7  not to much time a go, so for mysql 8 you need wait a lite more.

But yes maybe you can upgrade but vesta internally maybe fail in some functions lie "store and restore passwords"

**Comment by skyhigh119** [comment]
@Skamasle , thanks for information.., so i think vestaCP is better with MySQL 8.0.

**Comment by nepohex** [comment]
@Skamasle how about now? Can I upgrade to Mysql 8 at Ubuntu 18.04 and VestaCP ?

**Comment by Skamasle** [comment]
HI

I test mysql 8 in debian 9, and add some code to vestacp in #1805 and #1806 this need be tested but works, but in my end, I cant upgrade mysql from ubuntu 18, I have some problems and broken all not know why, but I install vesta in debian 9 with mysql 8 support without problems, you can read it here 

https://forum.vestacp.com/viewtopic.php?f=14&p=75504#p75504

But I NOT recommend swich to mysql 8 in vesta because not is tested, of course if you want test not in production or in production with your OWN RISK you can, but  I recommend you wait to official patch and support

But in my test works fine, can create, databases and all works, but I need test much more, like backups creation, restoration and other functions

**Comment by skyhigh119** [comment]
Thx for information!, vesta is best with mysql 8 soon!

**Comment by anton-reutov** [comment]
Vesta installs all packages from official repositories of OS, maybe support for 8.0 will be later
