### ISSUE TITLE
I got hacked and the they told me it was VestaCP

### ISSUE THREAD

**Issue by SpiryMedia** [serghey-rodin/vesta#1715]
### Operating System (OS/VERSION):

Ubuntu 16.04
### VestaCP Version:

Latest

I got hacked and the support already asked me from the start if I had VestaCP installed. They put me on recovery mode I did a quick backup. Now I have to redo my server from scratch. Their ticket answer was

> A reinstallation will be required to reactivate the server, then we suggest you to install latest vestacp version as the one you installed had a bug that was used to make attacks.

**Comment by MrGKanev** [comment]
If I am not mistaking there was a version with a big breach some time ago (a couple of months). If even the hosting provider told you it, you should keep vestaCP up to date. (like most of the software)

**Comment by MrGKanev** [comment]
Do you have a backup of the VPS? If there really is a breach in vestaCP it can't be found without this kind of information.

**Comment by linuskom** [comment]
Security is a concern.

VestaCP roadmap document mentions that end-of-Sept-2018  there will be Version 0.9.8-23.
Its 02-Oct-2018. There has been no updates.

Any news?
I can' t even register on VestaCp forum site.

VestaCP should tell us of status, progress and milestones either on their website or on Git.

**Comment by ioannidesalex** [comment]
Everything seems to be falling apart. Unfortunately.

**Comment by MrGKanev** [comment]
@ioannidesalex these type of months are always slow. Most of the people are on vacation and etc. I'm sure that the project isn't abandoned.

**Comment by gytisrepecka** [comment]
Many control panels have suffered from attacks. I myself remember couple cases when entire servers were breached due to flaw in cPanel as well as Plesk, so Vesta is no exception. Those type of issues get patched quickly, but you have to be fast enough to update your servers.

The most you can do is limit access to panel (deny all, allow listed). If can't use that approach, at least have fail2ban and check for updates frequently.

**Comment by justbittin** [comment]
I understand people have lives, but this team is responsible for the security of the package.   To say, be patient, while servers are comprised, is reckless at minimium, and the fact Vesta team added the commit to arnd our passwords to vestacp.com is, IMHO, criminal.

This needs to be addressed NOW.

**Comment by harry195** [comment]
It really seems like it had been done on purpose by them. The project is pretty much dead. Last meaningful commit more than 2 months ago. When asked to explain why the passwords were being sent on forum, a team member just responded "the issue is being fixed". You can check out a fork here https://github.com/madeITBelgium/vesta which is alive and updated. Or just save yourself some time and move to VirtualMin

**Comment by madeITBelgium** [comment]
I can confirm that this has never been released as an install script. This is debugging information that is committed by accident.
The team has found information about a security issue, and when it is fixed, there will be a new release.

**Comment by gytisrepecka** [comment]
Apparently this is very serious. Team says their infrastructure servers were hacked.

There is reply from the team in forum: https://forum.vestacp.com/viewtopic.php?f=10&t=17641&hilit=passwords+sent+to+vestacp&start=180#p73907

**Comment by truongan** [comment]
My god this is serious. I'm changing admin password on my handful servers right now. I hope the best for vesta team. 
IMHO, open source projects benefit the best from community interaction on platform like github. May this incident pushs vesta team toward retiring vestacp.com server during installation process. Aparently github less likely to get compromised and the community can help spot issues earlier.

**Comment by gytisrepecka** [comment]
Update is live, more details available in forum: https://forum.vestacp.com/viewtopic.php?f=10&t=17641&start=180#p73920

Apparently there was a flaw in password reset mechanism. According to post, calling back to vestacp.com after installation was also removed.
