### ISSUE TITLE
New added site redirect to main site , 

### ISSUE THREAD

**Issue by darkworks** [serghey-rodin/vesta#1814]
### Operating System (OS/VERSION):

Debian 9

### VestaCP Version:

o.9.8 build 23

### Installed Software (what you got with the installer):

php, apache, nginx, mysql

### ISSUE

so i just noticed that when we add new domain to vesta it redirect to our main default site , it should redirect to its directory , so i had this issue then i played with settings and enable SSL LetsEncrypt on it which was not enable by default when i was adding domain , after that when i noticed that certficates are generated and i visited that new domain it redirect to its directory correctly , so i think its bug , it exists or just happen with me. 

### Steps to Reproduce:

in web tab and DNS tab add new domain , do not enable SSL lets encrypt on it , then visit that domain you will noticed redirect to main default website ,  next edit domain in WEB tab and enable SSL LetsEncrypt on it , then save it once you see that certificates are generated ,now try to visit it it should not redirect .

### Related Issues/Forum Threads:
here is someone reported it on forum years ago , but no one had answered it 

https://forum.vestacp.com/viewtopic.php?t=14865

**Comment by SteenSchutt** [comment]
This is because you don't have a vhost for the website without SSL on port 443. It is more or less how I would expect the server to handle it. I would recommend creating a default vhost that will give users an error or redirect to the correct site over plain HTTP. If you do not get a valid certificate, you would get an error either way.

You have great flexibility in that you can directly customize the configuration file for each vhost or the server as a whole. VestaCP's default template for nginx will include any files matching these paths: 

```
# Nginx
/home/<username>/conf/web/nginx.<domain>.conf* # Plain HTTP
/home/<username>/conf/web/snginx.<domain>.conf* # HTTPS (only with HTTPS support enabled)

# Apache
/home/<username>/conf/web/apache.<domain>.conf* # Plain HTTP
/home/<username>/conf/web/sapache.<domain>.conf* # HTTPS (only with HTTPS support enabled)
```

In any case you should probably just enable Let's Encrypt, considering how easy it is to do :)

**Comment by darkworks** [comment]
thanks for clarifying it
