### ISSUE TITLE
Roadmap vs version ?

### ISSUE THREAD

**Issue by jodumont** [serghey-rodin/vesta#1857]
Hi;

### Which of these affirmation is true ?

1. It's already fall and we all missed summer _(if it's schedule for September 2019)_
2. We are back to the future (_September 2018_), but still missed summer
2. Surprise VestaCP is ready IPv6
3. 0.9.8-23 is not the Version of VestaCP

or another way to say it; I think the versioning is messing with us
![image](https://user-images.githubusercontent.com/5204724/55866936-b3fb2400-5b81-11e9-89ff-d63037001d8a.png)

**Comment by luizjr** [comment]
How to use relay in Exim?

**Comment by luizjr** [comment]
> How to use relay in Exim?

I also think that this roadmap is not completely in line with what exists.

I believe that @serghey-rodin @anton-reutov .... Should only focus on a distribution (Ubuntu of preference) to improve only on it, so we will be able to analyze and treat the problems that occur faster.

I still believe vesta is the best for the purpose, but community support should be greater to evolve.

**Comment by Rolige** [comment]
@luizjr CentOS its the preferred system for excellent by all hosting companies because is the most secure and free OS of Linux, so, completing your comment, Ubuntu and CentOS could be in my opinion the two OS to which should give continuity, greater focus and thus generate a better VestaCP.

**Comment by MrGKanev** [comment]
@Rolige CentOS isn't more secure than most of the modern Linux based OS-s. It's picked because it's more stable. All the packages there are a bit old but stable. (which has its minuses) 
But maybe your right about the two OS only part. Ubuntu is Debian based so maybe just remove Debian from the equation? Ubuntu has more tutorials publicly and people know it more.

**Comment by kristankenney** [comment]
I have to agree with @MrGKanev, CentOS is really no more secure than Debian-based releases, but more stable in some cases but there are drawbacks and it's a marginal improvement in stability.

For reference, we've been working on a fork of Vesta called [Hestia](https://github.com/hestiacp/hestiacp) that is Debian/Ubuntu-specific and does not support CentOS or Red Hat Enterprise Linux (RHEL), and this is because we believe that the Control Panel should be tightly integrated with the underlying operating system to provide the best performance, reliability, and security. This allows us to focus our development efforts where they matter most which is at the core of the Control Panel. If you'd like to try it out please feel free, feedback and contributions are always welcome.

**Comment by Rolige** [comment]
What is the classic evaluation when you have a doubt? If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.

If most hostings in the world use CentOS as base system for their servers, for some reason it must be.

**Comment by kristankenney** [comment]
> What is the classic evaluation when you have a doubt? If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.
> 
> If most hostings in the world use CentOS as base system for their servers, for some reason it must be.

I'm sorry, but I have to disagree here. There's nothing wrong with using Debian or Ubuntu as the base for a hosting control panel, whether it be powering web content, DNS services, mail services, etc. What matters most is the implementation, design, and security of the product and the server as a whole from an out-of-the-box configuration and that needs to either be done by the administrator by hand or the installation routine to ensure security remains top-of-mind.

Just because it has wheels doesn't mean that it's the best solution for the task at hand. Do you want to drive an old beat up car or something more modern, efficient, and reliable? The problem with supporting CentOS and RHEL alongside Debian and Ubuntu is that they use two separate packaging systems and require another set of installation scripts and additional logic and backward compatibility shims throughout the system due to different daemon names, file/folder path locations and more.

**Comment by luizjr** [comment]
> > What is the classic evaluation when you have a doubt? If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.
> > If most hostings in the world use CentOS as base system for their servers, for some reason it must be.
> 
> I'm sorry, but I have to disagree here. There's nothing wrong with using Debian or Ubuntu as the base for a hosting control panel, whether it be powering web content, DNS services, mail services, etc. What matters most is the implementation, design, and security of the product and the server as a whole from an out-of-the-box configuration and that needs to either be done by the administrator by hand or the installation routine to ensure security remains top-of-mind.
> 
> Just because it has wheels doesn't mean that it's the best solution for the task at hand. Do you want to drive an old beat up car or something more modern, efficient, and reliable? The problem with supporting CentOS and RHEL alongside Debian and Ubuntu is that they use two separate packaging systems and require another set of installation scripts and additional logic and backward compatibility shims throughout the system due to different daemon names, file/folder path locations and more.

@Rolige  and @MrGKanev at no point did I say that CentOS is bad.
But the intent of maintaining only debian-based systems is that you can leverage or have just one script to do the same in both.

When you add CentOS to the equation it becomes more difficult to solve possible problems with greater agility.

Why did I suggest Ubuntu? Precisely for the community involved and for being more updated (frequency) in packages which makes it more agile and modern in problem solutions.

For the stability issue, simply provide one or more sources for outsourced software. It would also be interesting to use a VestaCP-LTS or VestaCP-Beta version and even VestaCP-Dev.

All I did was give some ideas since the project maintainers are short on time.

**Comment by jodumont** [comment]
@Rolige I'm sorry to inform you than disabling SELinux, which most project do; makes CentOS/RedHat as weak as any other Linux

**Comment by jodumont** [comment]
it seams the roadmap vs version as being adjusted with the last release
http://vestacp.com/roadmap/
