### ISSUE TITLE
Unable to renews letsencrypt SSL - 400 error

### ISSUE THREAD

**Issue by progcode** [serghey-rodin/vesta#1901]
Operating System (OS/VERSION):
Ubuntu 16.04.6 LTS

VestaCP Version:
0.9.8 Release 24

Installed Software (what you got with the installer):
Default vesta install

Steps to Reproduce:
Try renew any Letsencrypt ssl cert via cpanel. It will returns 400 error.

Related Issues/Forum Threads:
https://forum.vestacp.com/viewtopic.php?f=11&t=18593.

**Comment by anthonyrossbach** [comment]
Yes the fix is to edit the file `bin/v-add-letsencrypt-domain` and replace the line

`well_known="$HOMEDIR/$user/web/$rdomain/public_html/.well-known"`

with 

`well_known="$HOMEDIR/$user/web/$domain/public_html/.well-known"`

You can see this here: [https://github.com/serghey-rodin/vesta/commit/25706abfb30e5b01d6fb604a78df5d2d4da8a7b4](https://github.com/serghey-rodin/vesta/commit/25706abfb30e5b01d6fb604a78df5d2d4da8a7b4)

**Comment by progcode** [comment]
This is already $domain param and not working.

**Comment by mtacore** [comment]
Works perfectly in HestiaCP.

**Comment by progcode** [comment]
Lol.

**Comment by progcode** [comment]
This solution is working: https://github.com/serghey-rodin/vesta/issues/1908#issuecomment-506993223

...oh and this the worst product support what i ever seen
