### ISSUE TITLE
Is Vesta project dead???

### ISSUE THREAD

**Issue by AntonKirilov** [serghey-rodin/vesta#2006]
I tried to get this answer on forum - https://forum.vestacp.com/viewtopic.php?f=10&t=19905 - but nobody from official members replied.

I'm just trying to get their attention - if they are live.

**Comment by Lupul** [comment]
Hello @AntonKirilov, I don't have a answer to your question but if you're trying to get in touch with the Vesta members to privately disclose a security vulnerability, please give HestiaCP team a heads up too. (contact details are on the "Security Policy" page on our github repo)

**Comment by Neustradamus** [comment]
Who manage the official website and social networks?

I would like to move the repository in an organization and create a team with all forked developers.

The goal is to have only one project managed by a real team which improves the code, adds supports and solves security problems.

@serghey-rodin: Can you contact me and give me all rights?

Thanks in advance.

**Comment by dpeca** [comment]
@Neustradamus 
do you personally know Serghey?
Because if not, I can't see why he will give it to you, since he didn't give it to very close friends (@anton-reutov for example), or to most active developers (me or @tjebbeke or any other developer with hundred commits and trust built over the years...)

**Comment by Neustradamus** [comment]
@dpeca: Badly not, but the problem is that currently Vesta CP must not be used in the World.
My goal is to create a team (included you) and solve all missing features/supports and vulnerabilities and of course do not stop the development of Vesta CP.
I think it is a good and serious project.

**Comment by Lupul** [comment]
@Neustradamus this is the reason other forks have started years ago.
Issues were left unanswered, pull-requests were ignored. Even important functionality like IPV6 support which [was proposed](https://github.com/serghey-rodin/vesta/pull/1139) in 2017 was ignored until it got obsolete and un-mergeable. Same for multiphp support. So much community energy was wasted...

**Comment by dpeca** [comment]
I must agree with @Lupul, I didn't have other choice.
For most fixes I waited for months to be pushed in repo... that slowed down my developing process.
Secondly, I can't reach Serghey when I want to ask him if I have a permission to add something to Vesta.
Simply, he obviously dont have a time to even answer on my mail, I believe he is really busy.
This way, with my fork, nobody slows down me, and I can change in code whatever I think I should change.

**Comment by dreiggy** [comment]
I have proposition for @dpeca, @Neustradamus and other DEVS to create a new fork VestacpNG (NG - stands for NextGeneration) and make a easy way for users to move their current deployments to new repo.

**Comment by anthonyrossbach** [comment]
I second the idea of a global version and a way to run a script to port over from the old repos to the new one. @dpeca and @dreiggy I also because I rely on this a lot and have ported it myself for my own use replacing the scripts after install I want this project to be back on track and will cover and run all and any servers needed to have a new repo going (shared access between any main devs so abandonment cant happen again).

I have access to a large cloud backing and my company uses (although modified and will always be modified) version of vestacp I want the core to live on.

**Comment by ScIT-Raphael** [comment]
@dpeca and I have already discussed about creating a shared repository based on a fork of Vesta. This is not to keep the project alive, but to secure the existing server installations against already patched and upcoming exploits - also to give users more time for a migration.

With Hestia and MyVesta there are already two forks that are working both on the further development of Vesta. I don't assume that it would make sense to create a third fork next to them.

We also try to support CentOS and IPv6 as next step - after the release of Hestia 1.2.0 which is planned for Monday and brings a lot of new features (https://github.com/hestiacp/hestiacp/blob/master/CHANGELOG.md). The work on the CentOS integration has already started with the support of a new dev - but a release date cannot be predicted yet.

**Comment by Neustradamus** [comment]
The goal is to have only one, a "merging" of MyVesta and Hestia if it is not possible to have a best Vesta CP directly...

-> A best:
- developer team
- support
- security
- ...

**Comment by ScIT-Raphael** [comment]
Hestia and MyVesta are very different, the code structure of Hestia has already been heavily modified and is no longer directly compatible with Vesta - although of course Vesta backups can be restored.

In the end, every user has to decide for himself whether he prefers to use Hestia or MyVesta. If he uses many modifications that strongly depend on the existing Vesta structure, MyVesta is definitely an advantage. Hestia on the other hand offers many new features, MultiPHP, Mail SSL, Filemanager, JailSFTP just to name a few. However, a new installation and the restore of backups is necessary, a direct migration from Vesta to Hestia from existing systems is not supported.

**Comment by dpeca** [comment]
Merging is not possible, and it will not be practical - I wrote here why - https://forum.vestacp.com/viewtopic.php?p=82536#p82536

**Comment by dpeca** [comment]
But, regardless we can not merge, both forks has very good mutural collaborations - sharing fixes and features...

**Comment by anthonyrossbach** [comment]
Then maybe a translation layer is more important, building a way for servers to migrate from one to the other without reinstall. Wondering if it would be possible to use the backup feature to remove vestacp but not it’s data files (maybe move) install hestacp and then import the accounts from backups even if stored externally. A process that can be one script one run to fully switch and keep things like settings, name servers, packages and so on that make it a pain to just start from scratch without a lot of downtime. A script that can move as many settings as it can before wiping and going over the user files list and recent backups to do restores would improve the migration making it many times faster.

**Comment by ScIT-Raphael** [comment]
@anthonyrossbach I would not say that this is impossible, but it would need a lot of work to get it working properly - due to the massive changes we did, our advice was always to install on a fresh system.

If you would find time to do some testings, that would be awesome and a big help for the community! Probaly all you need to know is the changed installers (https://github.com/hestiacp/hestiacp/tree/master/install) and also the upgrade steps (https://github.com/hestiacp/hestiacp/tree/master/install/upgrade/versions).

**Comment by dpeca** [comment]
You can convert Vesta to myVesta easily - https://github.com/myvesta/vesta/blob/master/src/deb/for-download/tools/convert-vesta-to-myvesta.sh
Of course, Debian only.

**Comment by anthonyrossbach** [comment]
I may for our internal use do exactly that @ScIT-Raphael. We do use DigitalOcean and a modified vestacp that has been minified (removed panel and so on). The downside to @dpeca's solution (I have that saved also as reference and will be looking into using it as a starting point) is that we use Ubuntu for everything.

The up side is our backups are external on B2 and we have our own systems for managing resources on the servers so we can actually use DO to reset the image and install and restore from VestaCP backup files on B2. The only downside is a few things missing from HestaCP that we use ATM (last time I checked) like B2 backups although I may just provide our changes to the main HestaCP as a pull request.

I just really personally liked the simplicity of VestaCP and am always in the mind set of less is more when it comes to the size of the panel and changes, making it easer to solve problems that arise (but that is me).

I really do appreciate the input on this even though it did not fit with the original statement of this issue but hopefully it results in a method for everyone to migrate.

**Comment by ScIT-Raphael** [comment]
> The only downside is a few things missing from HestaCP that we use ATM (last time I checked) like B2 backups although I may just provide our changes to the main HestaCP as a pull request.

That's the absolut right way to go, we would love to implement it - also the backup engine hasnt changed much, so it would be probaly only a copy and paste of your existing code.

I would also love to discuss with you, what else you miss in hestia. If you want, you can send us a short mail to info@hestiacp.com - so I could invite you to our slack group.

**Comment by anton-reutov** [comment]
Hi,
Vesta is not dead, but at the last time Serghey Rodin and other team members is very busy. We are working under new front-end interface and Debian 10 , CentOS 8 support.

**Comment by ScIT-Raphael** [comment]
Ok, good luck. But don't forget to also add support for Ubuntu 20.04. But prior of all that, please - PLEASE release a new version with the patches @dpeca already added. Just in case you mean it serious...

**Comment by anthonyrossbach** [comment]
@ScIT-Raphael  I may take you up on that. Also @anton-reutov yes, from all indication Vesta is dead as the last update was in October, and before that it was almost the start of the year. Not a single security patch has been pushed out that has been added to the repository so users are forced to patch files by hand. If it's not dead then allow someone else to actually push the changes out and support users instead of leaving them to figure it out on there own.

**Comment by Neustradamus** [comment]
Not easy to merge, but it is possible with a little time...

The goal is to have a real software with all OS compatibilities (not only Debian or not only Red Hat, etc.).

**Comment by Neustradamus** [comment]
Dear @anton-reutov and @serghey-rodin,

I think that it is time to move this project in a real developer team which will permit to have a future about Vesta CP.

Like you can see, we are several to want it...

Currently, all people which use Vesta CP are not safe.

Thanks in advance.

**Comment by ScIT-Raphael** [comment]
@Neustradamus @dpeca stated already his situation and pointed to the forum thread - currently I dont think there is anything to merge. Hestia will stay Hestia, MyVesta will stay MyVesta. The communication between our two forks is awesome, we do not see us as competitor.

**Comment by dpeca** [comment]
@Neustradamus 
Once again, merging is not possible.
Even in hypothetical situation if @serghey-rodin would give me access to official repo - the maximum that I can do is to build current github code (with latest fixes) and push it to official apt/rpm repo (I always said that I can help him about that, as well as Deb10 support).

**But**, even if he gives me full rights to do whatever I want with code (to build new features), **I would NOT** accept it, because I don't have time to maintain CentOS and Ubuntu support.
Supporting 3 distributions is wasting a time for me, and great way to make too many bugs due 3 different enviroments.
I talked about here - https://forum.vestacp.com/viewtopic.php?p=82021#p82021

Once again, I can help only with Debian.

**Comment by anthonyrossbach** [comment]
Why merge when really for it's use Hestia is the larger and more feature rich version as it is, it makes no sense to spend the time to move anything over anything or try and replace the original VestaCP as any future install can just use HestiaCP @Neustradamus. The only upside we can hope for now is a easy transition path for older installs that may be to large to reliably replace without massive downtime.

**Comment by anthonyrossbach** [comment]
I agree with @dpeca and think the core is fully dead at this point and takes to much time to work on with a small team, thats why if we cant have the best option for keeping VestaCP alive we should move towards easy migration paths and work on improving the other 2 alternatives. I know I will in a few weeks or a month start porting over my modifications and changes to HestiaCP and start doing pull requests with new features and modifications (that are generic for everyone).

**Comment by arafatx** [comment]
I love VestaCP because it has the lowest system requirement amongs other web control panels. You can install it on a server less than 1GB RAM. The UI was fast and I really like it. I remember last time, I bought a complete set of addons feature just to support devs even that time I knew that VestaCP was not ready for production because of many security flaws. So I gave my trust and time to devs but I was surprised they couldn't make it on time until people started to talk deep about security in VestaCP and that issue went viral over the internet.

That time I even felt sad, when he said that he is not gonna rewrite codes for basic security practice because of thousand line of codes. That was the time when I felt VestaCP is dead. As a server administrator I still want VestaCP He should have gave his project to somebody else and let others to rewrite the codes. Now even this project is alive, the bad reputation from the past has damaging the brand name. If security in VestaCP has improved a lot, they should rebrand and I believe many customers from DA and Cpanel will not hesitate to move into "Brand New Vesta CP"

**Comment by anton-reutov** [comment]
only Serghey has access to the repository and only he can release a new version. We plan to make it possible for each team member to release a new version.

**Comment by anton-reutov** [comment]
> You can install it on a server less than 1GB RAM. The UI was fast and I really like it.

New version with new front-end will be even easier and faster. File Manager for ex. already done.

**Comment by anthonyrossbach** [comment]
@anton-reutov basically this project is dead if users are forced to find fixes on there own, social presence by the project is gone, last update is almost a year ago and the update before that also was a long time ago with little changes between updates.

There has been security changes made a few times that have not been released as a version and sites are at risk due to the lack of action.

Just talk to us!! 

Will the updates be pushed out soon (that are already committed)

When will the project be worked on again.

When?

Why is nobody willing to be social on this project and just leaves everyone to figure it out on there own and do there own patches. It’s not like it’s a free project, I used it a lot and payed for SFTP jail many many times. That’s built in for free and expanded on with projects like HestiaCP as well as per mail domain SSL, main server TLS via LE, and more that are really lacking on vestacp.

With no admin communication, lack of security updates making it non usable in production, and basic communication this project IS dead.

**Comment by blondie101010** [comment]
I sadly have to agree, and felt I had to let go of the illusion over a 
year ago.  It's an appealing project but it's essentially unmaintained.

**Comment by anton-reutov** [comment]
@anthonyrossbach I will find out all information from Serghey and let you know when the new version is released.

**Comment by Neustradamus** [comment]
@anton-reutov: It is possible to see with @serghey-rodin about a transfer/move of this repository in an organization instead of personal account, I am ready to change this dead project etc.
What is your email?
Thanks in advance.

**Comment by anthonyrossbach** [comment]
Why do you @Neustradamus keep trying to take control when you have not even added any code or anything to this project...

**Comment by AntonKirilov** [comment]
> Hi,
> Vesta is not dead, but at the last time Serghey Rodin and other team members is very busy. We are working under new front-end interface and Debian 10 , CentOS 8 support.

@anton-reutov 
Just to see how active development looks like - myVesta changelog - https://github.com/myvesta/vesta/blob/master/Changelog.md

**Comment by vestacp-user** [comment]
100% Agree, simply the fact that it cannot be installed on Debian 10 and even more that Debian 10 is not the reccommended Debian version install is a HUGE RED FLAG.  Who cares about a "...New version with new front-end will be even easier and faster..." if the current Stable release of Debian (Debian 10 Buster at the moment) is not supported... seriously...   Sound like smokescreen to me.

I use VestaCP but am trasitioning to HestiaCP and myVestaCP.  I am undecided for the long term, but I am hoping that everyone consolidates into one, it is better for the ecosystem.  

I agree with @dpeca that it is better to only support one distro if resources are limited.  Subsequently, if other contributors wish to support other distros, all the better.  Debian 10 (Stable) has everything that VestaCP requires and it is a common denominator across many distros, including Ubuntu.  Ubuntu has more rapid release cycles (still based on Debian) so if you want the same effect as Ubuntu, you can just have a Testing branch of VestaCP for Debian Testing (currently Debian 11 Bullseye) which should have all the most recent version of all packages similar to the more recent releases of Ubuntu.  This has two advantages, it prepares Vesta for the next Stable release of Debian and also brings VestaCP closer to Debian derivatives that are on a faster release cycle. 

Basically, support Debian Stable and have a working branch for Debian Testing and you basically cover a large part of the linux distros with only small additional deltas that others can contribute if motivated.

**Comment by dpeca** [comment]
@vestacp-user 
When I made support for Debian10, it took me 2 days, but just because I didn't have finished compiler script (Serghey has it, but didn't make it public)
@ScIT-Raphael help me a lot with that, because he already made it for Hestia.

For installer modifications it took me only few hours.

Deb9 vs Deb10 differences was very small.
Actually, phpmyadmin installer took me most time, because Debian10 don't have phpmyadmin package at all, so we were forced to make installer for phpmyadmin.
Except that, modifications on vesta-installer script was minor when I made Debian10 support.
Without troubles with making phpmyadmin installer and without troubles to make compiling script from the scratch, Debian10 support could be made for few hours.

Basically, when Debian11 Bullseye come close to be released - I'm pretty sure we can make support for it in one single day.

**Comment by ScIT-Raphael** [comment]
Thanks for the release of a fixed version after weeks, happy here that the users get now a probaly secure verdion @anton-reutov @serghey-rodin! https://github.com/serghey-rodin/vesta/releases/tag/0.9.8-27

**Comment by ScIT-Raphael** [comment]
@anton-reutov what I don't understand: How can you suport Debian 10 without any modification to the installer script? From the Hestia side I know, that there are multiple changes needed to the script due to changed dependencies/software.

**Comment by dpeca** [comment]
As I can see, tag is "Pre-release".
Since there are only my security and bugs fixes, it's only that, fixes.
Maybe @serghey-rodin will add Deb10 support later.

But main question is did @serghey-rodin run builds for apt/rpm repo.

**Comment by ScIT-Raphael** [comment]
@dpeca you're right, I missed the "pre-release" tag, also just checked on one of my last vesta system running ubuntu 18.04 - there is no update available:

```
root@xxx:~# apt-cache policy vesta
vesta:
  Installed: 0.9.8-26
  Candidate: 0.9.8-26
  Version table:
 *** 0.9.8-26 500
        500 http://apt.vestacp.com/xenial xenial/vesta amd64 Packages
        100 /var/lib/dpkg/status

```

So unlucky but I've to answer your question with "no, @serghey-rodin did not run the builds". **So we still got a lot of insecure systems in the wild, when will you push them @serghey-rodin @anton-reutov?**

**Comment by Neustradamus** [comment]
Can you release an official build?
Instead of a test build?

And yes, Debian 10 / Centos 8.x are needed and all other improvements.

I think it is time to change the management team of the Vesta CP project.

**Comment by ScIT-Raphael** [comment]
@Neustradamus I think we discussed this enough times above...

**Comment by dreiggy** [comment]
> @anthonyrossbach I will find out all information from Serghey and let you know when the new version is released.

Do you have any information from Serghey?

**Comment by devius** [comment]
I there any hope we can use vesta on Centos 8 and Ubuntu 20.20?

**Comment by ScIT-Raphael** [comment]
@devius probaly no, project is still dead, exploits havent been patched. For ubuntu 20.04 i can suggest to try out hestia, we do not support non lts releases.

**Comment by devius** [comment]
> @devius probaly no, project is still dead, exploits havent been patched. For ubuntu 20.04 i can suggest to try out hestia, we do not support non lts releases.

It is very sad to hear that vestacp is dying, I still rely on CentOS as my primary production system. I have already tested HestiaCP and it is great job! Thank you.

P.S. I still hope that VestaCP will revive soon and make some progress.

**Comment by ifaist0s** [comment]
First of all I would like to once more thank the development team of Vesta for starting this nice project. I had been using it used it on a few servers in the past and paid for the Addons to support the development. But soon after, I started to worry about its security issues that were mentioned in forum and Github. As a lot of people already said, security fixes were not getting through, so my servers were becoming rapidly a disaster waiting to happen.

Then I learned about Hestia. Installed it to try it out, reached out to the devs and got replies, even posted my own fixes and PRs which got accepted and merged into the code. Communication was and still is great. We are working together towards a common goal and I like that. So I setup new servers with Hestia and restoredalmost all of my Vesta backups. Most of the time the migration would be smooth. But in rare cases where I would face a problem, I was not worried too much, because I knew that someone would respond to my post/issue in a timely manner, unlike Vesta forum.

Why am I saying all these? It might be possible that Vesta is not dead. But what will be the point of bringing new Vesta functionality after most or all of the Vesta community and users have migrated to other projects? What will be the point of fixing security issues after people have worked/developed their own solutions? And most importantly... How will the Vesta team "convince" people that they are here to stay?

Speaking for myself, I don't think I would go back to Vesta, even if there were new releases, if there were new features, if there was more engagement. Unless of course Hestia started at some point to have the same problems as Vesta is having now. But even then, I would consider a totally different Control Panel.

**Comment by emekaorjiani** [comment]
Hestia Here we go thank you @ifaist0s for putting it this way I have plenty
of projects running VESTACP, and I think this is the end of the Road for my
beloved VestaCP, R.I.P VestaCP

**Comment by arafatx** [comment]
Maybe we should leave CentOS and focus more on Debian due to RIP CentOS news.

**Comment by Neustradamus** [comment]
Please note that CentOS is not dead: CentOS Linux 8 (the rebuild of RHEL8) ends but CentOS Stream 8 will be here.

It will be nice to support now:
- Debian
- Ubuntu
- Fedora
- CentOS
- CloudLinux
- Rocky Linux

**Comment by ScIT-Raphael** [comment]
@Neustradamus Did you noticed, what exactly CentOS Stream will be? I don't think anyone want to run his servers on beta software of RHEL.

If you want to have that amount of supported OS please go ahead, fork hestia, myvesta or vesta and start implement it. I think @dpeca and the hestia team are always open for os integrations.

**Comment by S-T-A-L-K-E-R-II** [comment]
Debian very good & stable, everything else is crap!

**Comment by dpeca** [comment]
@ScIT-Raphael 
Actually, I was always "hard line" about supporting multiple OSes :D
I was talking about it here - https://forum.myvestacp.com/viewtopic.php?f=23&t=89

**Comment by ScIT-Raphael** [comment]
@dpeca I meant it in a little sarcastic way. As soon as you start to support rpm beside deb, you start to understand how complicated it is and how much testing and time you need.

**Comment by dpeca** [comment]
Yup, madness, in short.

**Comment by lpalgarvio** [comment]
hey guys
are the efforts of combining these projects coming along?
like many people i was surprised that there is still no support for debian 10.
and then i found out about https://www.myvestacp.com/ https://github.com/myvesta/vesta and
https://github.com/hestiacp https://www.hestiacp.com/

**Comment by ScIT-Raphael** [comment]
@lpalgarvio If you mean merging myvesta and hestia, not planed at all: https://github.com/serghey-rodin/vesta/issues/2006#issuecomment-650321268

**Comment by Neustradamus** [comment]
@ScIT-Raphael: It is the problem, the goal is to have only one project for all OS.
It is logic, really logic and normal...

**Comment by ScIT-Raphael** [comment]
@Neustradamus Hestia is a indipendent project and isnt anymore compatible with vesta or myvesta. We already support debian and ububtu systems, the compiler has been already updated to also build rpm packages - currently the installer is missing.

I don't know what you try to reach, but I think you got informed already enough that your requests are useless and nonsense. It is impossible to takeover vesta, because Serghey is the only one with repository access and he doesnt react or build new packages anymore (so vesta is dead). Also merging myvesta and hestia isnt an option, because of the points you got already informed above and within this issue report.

Personaly I see myvesta as option to "fast" migrate existing debian system to a secure code base. Hestia is all about new features and a wider OS support, which need a fresh install but is still compatible with vesta backups.

**Comment by Neustradamus** [comment]
I think that you have not understand me.
I (and other) would like that Hestia supports Fedora and other OS too in more Debian/Ubuntu.

**Comment by dpeca** [comment]
@Neustradamus 
I think that you are not able to understand how much it is useless, how much it is a wasting of time, and how much bugs it cause.

**Comment by RevengeFNF** [comment]
> @Neustradamus Did you noticed, what exactly CentOS Stream will be? I don't think anyone want to run his servers on beta software of RHEL.
> 
> If you want to have that amount of supported OS please go ahead, fork hestia, myvesta or vesta and start implement it. I think @dpeca and the hestia team are always open for os integrations.

That's not true, a few days ago RHEL Team explained the new Centos Stream. Fedora will still be the beta one, the next major rhel version. Centos Stream will be the next minor version. That means Centos Stream will receive 8.4 a few days sooner, but they will both receive 9.0 at the same time.

"We’re making CentOS Stream the collaboration hub for RHEL, with the landscape looking like this:

Fedora Linux is the place for major new operating system innovations, thoughts, and ideas - essentially, this is where the next major version of Red Hat Enterprise Linux is born.

CentOS Stream is the continuously delivered platform that becomes the next minor version of RHEL.

RHEL is the intelligent operating system for production workloads, used in nearly every industry in the world, from cloud-scale deployments in mission-critical data centers and localized server rooms to public clouds and out to far-flung edges of enterprise networks."

**Comment by lpalgarvio** [comment]
The IT open source community is leaving CentOS and adopting the fork Rocky Linux, made by the same authors.

So consider CentOS dead as:

1. will loose community support
2. it will be maintained mostly / only by Red Hat, but we already have RHEL for that
3. it will be considered alpha / beta software, no point in using in production

Instead Rocky Linux is the way to go

https://rockylinux.org/

What is the Rocky Linux project?
"Rocky Linux is a community enterprise operating system designed to be 100% bug-for-bug compatible with America's top enterprise Linux distribution now that its downstream partner has shifted direction. It is under intensive development by the community. Rocky Linux is led by Gregory Kurtzer, founder of the CentOS project. There is no ETA for a release. Contributors are asked to reach out using the communication options offered on this site."

What do you mean, "its downstream partner has shifted direction?"
"The CentOS project recently announced a shift in strategy for CentOS. Whereas previously CentOS existed as a downstream build of its upstream vendor (it receives patches and updates after the upstream vendor does), it will be shifting to an upstream build (testing patches and updates before inclusion in the upstream vendor). Additionally, support for CentOS Linux 8 has been cut short, from May 31, 2029 to December 31, 2021."

So where does Rocky Linux come in?
"Rocky Linux aims to function as a downstream build as CentOS had done previously, building releases after they have been added by the upstream vendor, not before."

https://github.com/rocky-linux/rocky

**Comment by gytisrepecka** [comment]
How is Rocky Linux a way to go while all it has is a README in it's repo? Wait for working build at least.

**Comment by lpalgarvio** [comment]
> How is Rocky Linux a way to go while all it has is a README in it's repo? Wait for working build at least.

> Instead Rocky Linux is the way to go.
> But it will take time to mature, so would be wise to not put efforts in this for now.
> Instead Debian 10 and Ubuntu LTS 20.04 should have priority.

**Comment by gtavargas** [comment]
@dpeca , @ifaist0s, @anthonyrossbach. Greetings to all. I have read this entire forum from the first comment to the last one and like everyone I thank VESTACP for such an excellent project, it served me too much. But let me also explain why I have had so many package incompatibility failures with CENTOS. I support @dpeca in all his comments he has made here and in the VESTACP forum and on supporting several versions of the operating system for a panel, it is exhausting.

I can only ask with deep sadness before making the hard decision to change to VESTACP, which will be and will look more stable in the future to replace VESTACP, between MYVESTACP or HESTIACP?

Thank you.

**Comment by ScIT-Raphael** [comment]
> I can only ask with deep sadness before making the hard decision to change to VESTACP, which will be and will look more stable in the future to replace VESTACP, between MYVESTACP or HESTIACP?

I think this has already been discussed above, but the list in this issue is now quiet long :). MyVestaCP "only" supports Debian 10 and is the project from @dpeca, which he makes available to the public because he was asked for. HestiaCP supports all (LTS) versions of Debian and Ubuntu, which are not EOL - the development team is a bit bigger and we also have made more changes, in special to features like 2FA, MultiPHP, MailSSL, and so on. Both, @dpeca and the Hestia Devs, are in direct contact to discuss and fix security and other issues - we are not rivals.

I would suggest that you have a look at both projects and take that which will fit better to your needs :).

**Comment by dpeca** [comment]
@gtavargas 
> I can only ask with deep sadness before making the hard decision to change to VESTACP, which will be and will look more stable in the future to replace VESTACP, between MYVESTACP or HESTIACP?

You can read my post - https://forum.myvestacp.com/viewtopic.php?f=23&t=88

In short:
* myVesta = probably more stable than Hestia since I'm the only one developer and I'm very slow in developing new features (which leads to less bugs :D )
* HestiaCP = much more developers, much larger community, so many new features, much faster developing

We can not say what will be better for you.
As @ScIT-Raphael said, both project has very nice mutural cooperation about security fixes and other features, and we are happy and proud because of that  :)

**Comment by Shaman2** [comment]
Hi. MyVesta and Heatia work with Debian 10. This debian suit for VDS 4gb memory? Now I use centos 6.5 and all work well.

Heatia has nginx template for prevent DOS, limit email and secret URL? Which function has MyVesta which not has Hestia?

**Comment by dpeca** [comment]
@Shaman2 
About memory:
- https://forum.myvestacp.com/viewtopic.php?f=14&t=45
- https://forum.myvestacp.com/viewtopic.php?f=14&t=279
- https://forum.myvestacp.com/viewtopic.php?f=14&t=44

I think it's the same for both VestaCP/myVesta/HestiaCP

--------

As far as I know:
> nginx template for prevent DOS, limit email and secret URL
... those features are features of myVesta.

**Comment by anton-reutov** [comment]
New front-end interface for VestaCP and FM plugin already done.

**Comment by anton-reutov** [comment]
**dpeca**, how we can test the Debian 10 ?

**Comment by ScIT-Raphael** [comment]
> New front-end interface for VestaCP and FM plugin already done.

How about release new packages to the repository to fix the current exploits instead promising new features that arent visible on any github branch?

**Comment by dpeca** [comment]
@anton-reutov 
> **dpeca**, how we can test the Debian 10 ?

As I already described you in private message on forum before few months:

Use the installer and apt repo from my fork (myVesta fork) :
```
curl -O http://c.myvestacp.com/vst-install-debian.sh
bash vst-install-debian.sh
```

It will run installer that is adapted for Deb10 ( https://github.com/myvesta/vesta/blob/master/install/vst-install-debian.sh ) and it will also use **vesta-nginx** and **vesta-php** that is compiled for Deb10.
Both **vesta-nginx** and **vesta-php** will be downloaded from my apt server, because there is no other way (i can not push build to official apt.vestacp.com repo, and deb9 package will not work on deb10, so the only way was to build my own repo (myVesta repo) for deb10 packages **vesta-nginx** and **vesta-php** )

but, anyway, you can also compile **vesta-nginx** and **vesta-php** by yourself - https://github.com/myvesta/vesta/blob/master/src/deb/vesta_compile.sh

**Comment by gtavargas** [comment]
@dpeca , @anthonyrossbach,

Thanks for the answers and it is clear to me that we are in the community and the idea is to cooperate so that it grows, I am a big fan and lover of Open Source solutions such as: Ubuntu in its versions, Pfsense, Endian, Proxmox, Elastix (today Issabel), Zentyal, openmediavault, etc, etc, etc.

I hope these two projects prosper and are more solid. even more so if you have the collaboration and cooperation between MYVESTACP and HESTIACP that exists today. I wish the best of lucks.

I will try both and I will give you my points of view and hopefully I can, why not, contribute to improvements.

Greetings.

**Comment by Shaman2** [comment]
> those features are features of myVesta.

But you dont support 2FA, I right?

Which panel has on one server   nginx+php-frm and nginx-apache-php-fpm for different sites?

**Comment by dpeca** [comment]
@Shaman2 
> But you dont support 2FA, I right?

Right, Hestia has 2FA.

> Which panel has on one server nginx+php-frm and nginx-apache-php-fpm for different sites?

It's possible in myVesta but with few steps - example: https://forum.myvestacp.com/viewtopic.php?f=2&t=314

**Comment by Shaman2** [comment]
> It's possible in myVesta but with few steps

so I default setup "apache yes, nginx yes, php-fpm yes" ?

**Comment by ScIT-Raphael** [comment]
@Shaman2 I would suggest to switch over either to myvesta or hestiacp forum for your questions :).

**Comment by ScIT-Raphael** [comment]
@anton-reutov may I suggest to compile and release new packages or reopen this thread? There are thousands of vesta servers with unfixed exploits in the wild!

**Comment by anton-reutov** [comment]
> may I suggest to compile and release new packages or reopen this thread?

Hi,
I don't have access to the repo. I'll ask Sergey about it tomorrow. Also, dpeca will send me a list of bugs tomorrow. I think we will release a security version to finally close this issue.

**Comment by ScIT-Raphael** [comment]
Looking forward to your update tomorrow, don't let hang the users an additional year. If you do it, you should consider to stop the project or atleast inform the users about the current security issues.

**Comment by jaapmarcus** [comment]
@anton-reutov  If you speak him please inform him to renew vestacp.com it is about to expire...

**Comment by anton-reutov** [comment]
Ok
