### ISSUE TITLE
[Feature Request] MariaDB instead of MySQL

### ISSUE THREAD

**Issue by MLWALK3R** [serghey-rodin/vesta#207]
Would this be possible?

mariaDB has kind of been proven to be better IMO.

**Comment by MdNor** [comment]
+1

This should be easy to do. But I think its more of a design decision by @serghey-rodin 
MariaDB now come as default with certain major Linux OS'es. I think its worth the change for VestaCP.

**Comment by EminezArtus** [comment]
+1 for MariaDB

**Comment by serghey-rodin** [comment]
We are working on CentOS 7 support where you get MariaDB as default DBMS, but we will definitely consider MariaDB implementation in other distros. Thanks

**Comment by joubertredrat** [comment]
Hi guys,

+1 for MariaDB

Why not both mariadb and mysql as optional? I saw here that is possible to use postgres on VestaCP too, then set which will be default to listen on 3306 and another listen on 3307 as example.

My idea is strange, but can be a option.

**Comment by maszd** [comment]
+1 for MariaDB
waiting for this on next release vestacp
regards.

**Comment by Exadra37** [comment]
+1 for Perconna Server instead, i already use it in production with VestaCp.

I am using it, since more than 1 year in my 2 Linode VPS and in my Digital Ocean Dropplet without any problems.

Is very easy to replace. Basically you will replace your current /var/lib/mysql with the one you will extract from the perconna tar ball as stated in [StackOvrflow reply](http://stackoverflow.com/a/7981567) by member of Perconna staff. 
Make sure:
* you download the same mysql version of Percona, because if you replace it by the wrong version it will not work.
* to do backups, before you try replace Mysql with Percona.

If you want to install it properly as a replacement or as a new install, please see:
* https://www.digitalocean.com/community/tutorials/how-to-install-a-fresh-percona-server-or-replace-mysql
* http://planet.jboss.org/post/drop_in_migration_from_mysql_to_percona_db_in_two_minutes

If you make the option to use [Percona](http://www.percona.com/software/percona-server/ps-5.6) you should take advantage of [XtraBackup](http://www.percona.com/software/percona-xtrabackup) to perform your hot mysql backups ;)

If performance is your goal you may want to give a try to  [TokuDB](http://www.tokutek.com/tokudb-for-mysql/tokudb-vs-innodb/) that is available to use in [Percona since 2014/06/01](http://www.percona.com/blog/2014/07/01/percona-server-5-6-19-67-0-with-tokudb-ga-now-available/) and have also the benefit of reduce your storage needs for mysql.

TokuDB storage engine articles in Percona Blog:
* [Benchmark 1](http://www.percona.com/blog/2013/05/07/benchmarking-percona-server-tokudb-vs-innodb/)
* [Benchmark 2](http://www.percona.com/blog/2013/09/05/tokudb-vs-innodb-timeseries-insert-benchmark/)
* [Installation](http://www.percona.com/doc/percona-server/5.6/tokudb/tokudb_installation.html)
* [Using TokuDb](http://www.percona.com/doc/percona-server/5.6/tokudb/using_tokudb.html)

PS: if you need a new VPS, please use one of my referrall links to sign up for [Linode](https://www.linode.com/?r=aac1e7b9a19532e3092580439d945a54fcc66f62) or [Digital Ocean](https://www.digitalocean.com/?refcode=bcfccab39ee2)

**Comment by naurelijs** [comment]
+1 Can't wait MariaDB.

**Comment by Naizugai** [comment]
Please add MariaDB :)

**Comment by marcelloinfoweb** [comment]
+1 MariaDB

**Comment by naurelijs** [comment]
Any news?

**Comment by KeiroD** [comment]
Just follow [this guide I wrote for Vultr](https://www.vultr.com/docs/install-mariadb-on-ubuntu-14-04).

Easy peasy. Granted, it'd be nice to have VestaCP do it for you, but... yeah.

**Comment by naurelijs** [comment]
@KeiroD and now try to restart via Vestacp panel

**Comment by joubertredrat** [comment]
I tried a lot times, is hard to put mysql and mariadb on same host, but I haven't given up. I will try again

**Comment by KeiroD** [comment]
@naurelijs Works for me just fine? Starts via VestaCP panel and commandline just fine.

@joubertredrat Er... you're not supposed to run MySQL and MariaDB on the same server. MariaDB **is** MySQL. Don't do that.

**Comment by joubertredrat** [comment]
@KeiroD yes, The only problem is both use same folders, /var/lib/mysql is example.
If I can't make both works on same machine, I will try with docker and propose this here.

**Comment by KeiroD** [comment]
```
[10:34:48PM] <13Kradorex> Technically it's possible, but it's pointless.
[10:35:00PM] <04Keiro> You'd just get a lot of conflicts if you did.
[10:35:25PM] <13Kradorex> well actually, not really if you do it properly
[10:35:26PM] <04Keiro> Besides, only way to do that would be to segregrate them via chroot and using different versions of MySQL/MariaDB.
[10:35:41PM] <04Keiro> Or at least, that's how I'd do it.
[10:35:52PM] <13Kradorex> 1) Use a different Unix socket file or disable the unix socket on one or the other
[10:36:12PM] <13Kradorex> 2) Use different port numbers for the TCP Service listening on lo
[10:36:33PM] <13Kradorex> 3) Use different data directories
[10:36:46PM] <04Keiro> ... Indeed.
[10:36:48PM] <13Kradorex> 4) Use different tmp directories
[10:36:51PM] <13Kradorex> That should do it
[10:37:29PM] <13Kradorex> But it's again, rather pointless
```

You might want to try the above.

**Comment by darkworks** [comment]
follow :: https://talk.pr-cy.ru/topic/12001-guide-kak-bystro-nastroit-vps-v-kachestve-web-servera/

**Comment by slmcncb** [comment]
+1 for MariaDB

**Comment by DjDiLiSoFT** [comment]
+1 for MariaDB

**Comment by SysVoid** [comment]
+1 fuh mahrhiadeebee

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/92
