### ISSUE TITLE
Ubuntu 18.04 Installer broken

### ISSUE THREAD

**Issue by jaapmarcus** [serghey-rodin/vesta#2130]
### Operating System (OS/VERSION):

18.04 Ubuntu 

### VestaCP Version:

1.0.04

### Installed Software (what you got with the installer):

Default install without SOFTACULOUS 

### Steps to Reproduce:

# Connect to your server as root via SSH
ssh root@your.server
# Download installation script
curl -O http://vestacp.com/pub/vst-install.sh
# Run it
bash vst-install.sh

### Related Issues/Forum Threads:
2021-11-02 11:00:58 [WARNING] mysql_install_db is deprecated. Please consider switching to mysqld --initialize
2021-11-02 11:00:58 [ERROR]   The data directory needs to be specified.
mkdir: cannot create directory ‘/var/lib/mysql’: File exists
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Warning: Since password will be sent to server in plain text, use ssl connection to ensure password safety.
ERROR 1054 (42S22) at line 1: Unknown column 'password' in 'where clause'
Setting /usr/sbin/named to complain mode.
Adding user Debian-exim to group mail
Adding user dovecot to group mail
Adding user clamav to group mail
Adding user clamav to group Debian-exim
Synchronizing state of spamassassin.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable spamassassin
chattr: Operation not permitted while setting flags on /home/admin/conf
/usr/local/vesta/bin/v-update-firewall: line 164: /etc/network/if-pre-up.d/iptables: No such file or directory
/usr/local/vesta/bin/v-update-firewall: line 165: /etc/network/if-pre-up.d/iptables: No such file or directory
/usr/local/vesta/bin/v-update-firewall: line 166: /etc/network/if-pre-up.d/iptables: No such file or directory
chmod: cannot access '/etc/network/if-pre-up.d/iptables': No such file or directory
/usr/local/vesta/bin/v-update-firewall: line 164: /etc/network/if-pre-up.d/iptables: No such file or directory
/usr/local/vesta/bin/v-update-firewall: line 165: /etc/network/if-pre-up.d/iptables: No such file or directory
/usr/local/vesta/bin/v-update-firewall: line 166: /etc/network/if-pre-up.d/iptables: No such file or directory
chmod: cannot access '/etc/network/if-pre-up.d/iptables': No such file or directory
chmod: changing permissions of '/var/log/apache2/domains/xxxxx.bytes': Operation not permitted
chmod: changing permissions of '/var/log/apache2/domains/xxxxx.log': Operation not permitted
chmod: changing permissions of '/var/log/apache2/domains/xxxxx.log': Operation not permitted

**Comment by anton-reutov** [comment]
**SciT-Raphael**, You are very happy about Vesta's mistakes, I understand that :)  We are all know the reason

 **jaapmarcus** , we are working under new installers for Debian Ubuntu CentOS

**Comment by Pleskan** [comment]
@anton-reutov IMHO, there no talking about "happy/sad" about new release of VestaCP (after  2 years of being deep sleep), it's just the bare facts "as is"
You and other developers of new release didn't test it even in basics... so the results are exactly as it should be.
Again there is no emotions of gloating just the facts in the "Issues" tab.

**Comment by anton-reutov** [comment]
**Pleskan**  the matter is completely different. In some issue on github (I don't remember the number) we have already talked to **SciT** about this

**Comment by ScIT-Raphael** [comment]
> **SciT-Raphael**, You are very happy about Vesta's mistakes, I understand that :) We are all know the reason

Well, you interpret a lot into an emoji, probaly a bit to much. In that specific case here, it was just irony - it just proved that you shipped vesta on a friday night (!) without any minimal testing (a fresh install, maybe add a let's encrypt cert) and fucked up the mood of a lot of vesta users. This is a fact that I'm sorry to blow out that directly.

> **Pleskan** the matter is completely different. In some issue on github (I don't remember the number) we have already talked to **SciT** about this

You probaly mean the "why in every word, I'm negative against Vesta"-thing which I answered here: https://github.com/serghey-rodin/vesta/issues/2061#issuecomment-887565070

Also I never mentioned HestiaCP in any word, since you released v1.0 - you just came up with it again, due to the "emoji"-misinterpretation (no idea if this is a valid word), even when there would have been enough possibilities to do so.

Anyway, I'll not bother you anymore (expect probaly some emojis) - my main interrest, that you secure the remaining vestacp servers, is solved - hopefully not to much users will downgrade.
