### ISSUE TITLE
 All forwarded email does not delete.

### ISSUE THREAD

**Issue by rmalenko** [serghey-rodin/vesta#248]
All forwarded email does not deleted.
When I have unchecked Forward box - email continue forwarding

**Comment by tommyvallier** [comment]
Hi,

I'm experiencing this issue as well. Box is checked to not store forwarded mail - but a copy arrives in the mailbox as well as forwarding along.

Running Ubuntu 14.04.2. Confirmed that the router in /etc/exim4/exim4.conf.template is correct.

**Comment by atonit** [comment]
Hi Sergei,
I found the problem is the link to condition in localuser_fwd_only , which should be changed exim to exim4.
So, i'm on ubuntu 14.04, i went to /etc/exim4/exim4.conf.template: 
localuser_fwd_only:
  driver = accept
  transport = devnull
  condition = ${if exists{/etc/exim4/domains/$domain/fwd_only}{${lookup{$local_part}lsearch{/etc/exim4/domains/$domain/fwd_only}{true}{false}}}}

And now all is allright

**Comment by skurudo** [comment]
+1 for @atonit

**Comment by steffnomidi** [comment]
+1 for @atonit

**Comment by LouisUK** [comment]
+1 @atonit 

Works for me.
