### ISSUE TITLE
Don't hard-code HTTPS in links

### ISSUE THREAD

**Issue by nobodypb** [serghey-rodin/vesta#398]
While translating I recognized it is hard-coded to use https in PASSWORD_RESET_REQUEST and ACCOUNT_READY.
It would be nice if there was a setting to toggle between https and http in these links.
Because if the domain hasn't a valid SSL certificate, a normal user would be confused by the browser-warning.

**Comment by Exadra37** [comment]
All the urls should be in the code without the protocol and the the protocol being used will be assumed autocratically... so instead of  `https://example.com` we should have in code only `//example.com`.

A setting to enable enforcing https should be present, so that when we have a valid certificate we can enforce all users to use https instead of http.

**Comment by nobodypb** [comment]
+1

**Comment by SysVoid** [comment]
-1
#425

**Comment by skurudo** [comment]
Closed due inactivity.
