### ISSUE TITLE
Question: why 2 servers?

### ISSUE THREAD

**Issue by demil** [serghey-rodin/vesta#446]
Is there som benefit to have 2 nginx, and 2 php installed?

why isn't just main nginx and main php for runing vesta admin site also?

**Comment by thiagof** [comment]
Apache generally is more compatible with overall applications setup.
Nginx is layer to fast serve cache and static files.

But I've heard they are working on a nginx-only solution.

**Comment by demil** [comment]
You didn't understand question.

**Comment by SiteSplat** [comment]
yeah then its the two of us. In any case this is not the place for questions.  This is a place to file bugs and help the developers... If you have general questions I suggest you to look into : http://serverfault.com/

**Comment by tjebbeke** [comment]
When the control panel is down, your websites can be up or when your websites are down you can access you control panel.

**Comment by demil** [comment]
that is the answer. thank you.

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
It's too bad that nginx is used as a front server for everything. First, if the control panel (nginx) is down - everything is down because everything is served through the nginx. Now I have a problem with domain setup (it shows "it worked" instead of proper files) and I just can't debug it and can't access apache directly (domain:8080 is not working) to at least figure out what server is responsible for the error - apache or nginx. This mandatory excessive proxying adds more problems than solves.

**Comment by skurudo** [comment]
yetanotherusernamebecausegithubisbugged, there is 2 nginx: for websites - 80 port and for panel VestaCP - 8083 port. If control panel down, sites work just fine. If you have problem, please, try to post topic on bugs or better on forum (yes, we have one for problem and discussion) -> https://forum.vestacp.com

(it shows "it worked" instead of proper files) -- try to delete index.html first.
and welcome to forum ;-)
