### ISSUE TITLE
[Request] Please create vesta-release.rpm

### ISSUE THREAD

**Issue by ionescu-bogdan** [serghey-rodin/vesta#531]
To simplify the process of installing, updating and maintenance, please create:
`vesta-release-1.0.0.rpm`

If you need help I can do it but can not sign the package.

Thank you,
Ionescu Bogdan

**Comment by SysVoid** [comment]
Installation is simple enough as it is.
:-1:

**Comment by KeiroD** [comment]
@SysVoid Actually, while the install may be simple, I'm not sure if CentOS/RHEL has Vesta in their repositories.

I know right now that Vesta is easily obtained on `Ubuntu` via `apt-get` once you know what the signing keys are for Vesta. From this point on, Vesta is updated either automatically by itself or via `apt-get update && apt-get upgrade`.

It's not unreasonable to want to have a repository for CentOS-based servers.

**Comment by serghey-rodin** [comment]
The very first public release was named 0.9.7-x  because it included only 97% of what we've planned.
It means that 0.9.8 branch represents 98% of planned stuff. When we will have IPv6 support in production-ready state we will increase version to 0.9.9. As for the version 1.x.x it should overrun any other control panel :)

Eventually vesta's version will match desired string. But there are some things to work on.

**Comment by serghey-rodin** [comment]
Ah so it's not about package versions :) I'm sorry I'm too sleepy right now and misunderstood the context. 

Can you please explain me what is the benefit of having repo package? 
I'm asking because  guys from nginx and mongo for example aren't providing it:
http://nginx.org/en/linux_packages.html
https://docs.mongodb.org/manual/tutorial/install-mongodb-on-red-hat/

**Comment by KeiroD** [comment]
@serghey-rodin It's quite alright.

I suppose the benefit of having a repo package is that it's easier for you, the maintainer, to update everything via the `yum update && yum upgrade` method for those who don't want to have `vesta` auto-upgrade on its own.

**Comment by ionescu-bogdan** [comment]
The same benefit as the rest of the suppliers.
Control and management of packages from the repository. View details:

- CentOS
http://vault.centos.org/6.6/os/x86_64/Packages/centos-release-6-6.el6.centos.12.2.x86_64.rpm

- EPEL (Fedora)
http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
- Remi
http://rpms.famillecollet.com/enterprise/6.6/remi/x86_64/remi-release-6.6-2.el6.remi.noarch.rpm

- Nginx
http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

- MySQL
http://repo.mysql.com/yum/mysql-5.6-community/el/6/x86_64/mysql-community-release-el6-5.noarch.rpm


They update the repository using that package. We are talking specifically of:

- `/etc/yum.repos.d/vesta.repo`
- `/etc/pki/rpm-gpg/RPM-GPG-KEY-VESTA`

but we do not limit them...

Another benefit is the creation of a distribution (DVD) with all packages installed (including vesta-release) - `ready-for-production`.
For example, I'm using these DVD for installation on VMware ESXi.
