### ISSUE TITLE
Bind 9 cannot read zone file

### ISSUE THREAD

**Issue by rmalenko** [serghey-rodin/vesta#640]
Hi, 

I had got error
`zone que.com/IN: loading from master file /home/admin/conf/dns/que.com.db failed: permission denied`

named.conf after Vesta install
`zone "que.com" {type master; file "/home/admin/conf/dns/que.com.db";};`

when I place que.com.db into /etc/bind/ zone loaded successfully
`zone "que.com" {type master; file "/etc/bind/que.com.db";};`

In both cases que.com.db has 666 and admin:bind

Bind9
Ubuntu 14

**Comment by KeiroD** [comment]
How do I check my bind configuration for errors?

Simply run command as follows:

`# named-checkconf /etc/named.conf`

You may want to chroot to directory so that include directives in the configuration file are processed as if run by a similarly chrooted named:

`# named-checkconf -t /var/named/chroot /etc/named.conf`

If there is no output, the configuration is considered correct and you can safely restart or reload bind configuration file. If there is an error it will be displayed on screen:

`# named-checkconf /etc/named.conf`

Example Output:

`/etc/named.conf:58: open: /etc/named.root.hints: file not found`

Let us know if `bind9` is not set up correctly and we'll check more closely, please.

**Comment by rmalenko** [comment]
@KeiroD thank you to answer.

named-checkconf - gives no error

The issue looks like wrong permissions were set after install VestaCP

**Comment by seventhqueen** [comment]
hi. doing some tests with the vestaCP and  getting the same error

**Comment by Aporie** [comment]
Hey, same error here.

```
zone sd-xxxx.dedibox.fr/IN: loading from master file /home/admin/conf/dns/sd-xxxx.dedibox.fr.db failed: permission denied
déc. 30 20:20:31 orao-web-server named[28758]: zone sd-xxxxx.dedibox.fr/IN: not loaded due to errors.
déc. 30 20:20:31 orao-web-server named[28758]: zone domain.ttl/IN: loading from master file /home/admin/conf/dns/domain.ttl.db failed: permission denied
déc. 30 20:20:31 orao-web-server named[28758]: zone orao-web.net /IN: not loaded due to errors.
déc. 30 20:20:31 orao-web-server named[28758]: zone ns1.domain.ttl/IN: loading from master file /home/admin/conf/dns/ns1.orao-web.net.db failed: permission denied
déc. 30 20:20:31 orao-web-server named[28758]: zone ns1.domain.ttl/IN: not loaded due to errors.
```

```
-rw-r----- 1 root bind  735 déc.  30 18:34 ns1.domain.ttl.db
-rw-r----- 1 root bind  735 déc.  30 18:35 ns2.domain.ttl.db
-rw-r----- 1 root bind  856 déc.  30 20:04 domain.ttl.db
-rw-r----- 1 root bind 1047 déc.  30 17:42 sd-xxxxx.dedibox.fr.db
```

Have you found a solution ?

**Comment by alex-connor** [comment]
Does you use latest version of panel?

**Comment by Aporie** [comment]
I think I'm using 0.9.8-18 as I have softaculous. What's the best way to check vesta version ?

I found a [solution](http://www.cesarfileto.com/blog/2016/01/20/bind9-zone-example-comin-loading-from-master-file-homeadminconfdnsexample-com-db-failed-permission-denied/) but I think it has some security impact : 

In _/etc/apparmor.d/usr.sbin.named_

Add this line

`/home/admin/config/dns/ rwm,`

Underneath this line

`/etc/bind/** rw,`

And restart apparmor 

`service apparmor restart`
