### ISSUE TITLE
clamav and email problems related and solved

### ISSUE THREAD

**Issue by blare** [serghey-rodin/vesta#645]
Hello everybody,

I'm new to Vesta, just 24hours user, and I detected something strange in my email behaviour and related to clamav. Really strange, if is not documented, this may help others.

I have a clean CentOS7 Installation with latest vesta Version:0.9.8 (x86_64) Release:15.

I noticed this morning that ClamAV was running the whole night at 100% CPU usage, so I decided to stop the service under the "SERVER" tab.

After that, i was trying to set up my first email account, in my domain, and it seemed not to work fine. Thunderbird was returning: **"Error while sending the message. The mail server answered: Temporary local problem - please try later."**.

After looking on /var/log/exim logs, I read that clamd was logging a panic error:
**clamd: unable to connect to UNIX socket (/var/run/clamav/clamd.sock): No such file or directory**

Searching on Google I found this link https://bugs.vestacp.com/issues/122 which there was "Magic pill" comment on it. The commands were:

**mkdir /var/run/clamav/
сhown clam:mail /var/run/clamav/**

This solved both problems, the 100% CPU usage of clamav and the email server error.

Is this a bug? Did you noticed this behaviour?

Hope it helps!

**Comment by SysVoid** [comment]
I don't recall CentOS 7 being supported.

**Comment by SysVoid** [comment]
I'll take a quick look at the ClamAV install script.

**Comment by blare** [comment]
Thanks @SysVoid

**Comment by SysVoid** [comment]
Keep this open in case someone catches something I missed. Let the merge close it once someone verifies it works. :)

**Comment by blare** [comment]
Perfect, thanks again!

**Comment by SysVoid** [comment]
No problem. :)

**Comment by SPEC1AL1ST** [comment]
Problem back after server restart!

**Comment by blare** [comment]
Hi,

Which problem? 100% CPU consumption or the email one? both? Is the directory **/var/run/clamav/** still on the same place with the correct permissions?

You may have a look at your exim log ( **/var/log/exim** ) to see if some new error is appearing. It helped a lot in my case.

I still didn't rebooted my server, so I cannot verify it. Could it be related to something else (any other change related before rebooting the server)?

**Comment by SPEC1AL1ST** [comment]
Folder red moved after reboot

**Comment by ronshe** [comment]
Your solution worked for me:
mkdir /var/run/clamav/
сhown clam:mail /var/run/clamav/

**Comment by stevoh6** [comment]
Hi I found een better solution. Add mkdir and chown command to crontab.
Run command `crontab -e`, write and save those lines 
```
@reboot mkdir /var/run/clamav/
@reboot chown clam:mail /var/run/clamav/
```

**Comment by blare** [comment]
@coldplug also commented a similar workaround here https://github.com/serghey-rodin/vesta/issues/576#issuecomment-219569866

> Add these two lines into /etc/rc.local
> mkdir /var/run/clamav
> chown clam:mail /var/run/clamav

**Comment by stevoh6** [comment]
yeah, this works very well too :-D

**Comment by infinitnet** [comment]
Looks like this issue is back with clamav 0.99.2-1.el7 (when you restart your server after you update the RPM) and this time it's really weird. I tried all solutions suggested here and they did work pre version 0.99.2-1, but now they don't. It looks like clamav just silently dies right after it started. I also deleted all databases and downloaded them again with freshclam, so no issue there. It's this over and over again:

`Mon Jul 18 18:13:49 2016 -> +++ Started at Mon Jul 18 18:13:49 2016
Mon Jul 18 18:13:50 2016 -> Received 0 file descriptor(s) from systemd.
Mon Jul 18 18:13:50 2016 -> clamd daemon 0.99.2 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Mon Jul 18 18:13:50 2016 -> Running as user clam (UID 1001, GID 1001)
Mon Jul 18 18:13:50 2016 -> Log file size limited to 4294967295 bytes.
Mon Jul 18 18:13:50 2016 -> Reading databases from /var/lib/clamav
Mon Jul 18 18:13:50 2016 -> Not loading PUA signatures.
Mon Jul 18 18:13:50 2016 -> Bytecode: Security mode set to "TrustSigned".
Mon Jul 18 18:14:03 2016 -> Loaded 4651550 signatures.
Mon Jul 18 18:14:05 2016 -> TCP: Bound to [127.0.0.1]:3310
Mon Jul 18 18:14:05 2016 -> TCP: Setting connection queue length to 30
Mon Jul 18 18:14:05 2016 -> LOCAL: Unix socket file /var/log/clamav/clamd.sock
Mon Jul 18 18:14:05 2016 -> LOCAL: Setting connection queue length to 30
Mon Jul 18 18:14:05 2016 -> Limits: Global size limit set to 104857600 bytes.
Mon Jul 18 18:14:05 2016 -> Limits: File size limit set to 26214400 bytes.
Mon Jul 18 18:14:05 2016 -> Limits: Recursion level limit set to 16.
Mon Jul 18 18:14:05 2016 -> Limits: Files limit set to 10000.
Mon Jul 18 18:14:05 2016 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Mon Jul 18 18:14:05 2016 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Mon Jul 18 18:14:05 2016 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Mon Jul 18 18:14:05 2016 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Mon Jul 18 18:14:05 2016 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Mon Jul 18 18:14:05 2016 -> Limits: MaxPartitions limit set to 50.
Mon Jul 18 18:14:05 2016 -> Limits: MaxIconsPE limit set to 100.
Mon Jul 18 18:14:05 2016 -> Limits: MaxRecHWP3 limit set to 16.
Mon Jul 18 18:14:05 2016 -> Limits: PCREMatchLimit limit set to 10000.
Mon Jul 18 18:14:05 2016 -> Limits: PCRERecMatchLimit limit set to 5000.
Mon Jul 18 18:14:05 2016 -> Limits: PCREMaxFileSize limit set to 26214400.
Mon Jul 18 18:14:05 2016 -> Archive support enabled.
Mon Jul 18 18:14:05 2016 -> Algorithmic detection enabled.
Mon Jul 18 18:14:05 2016 -> Portable Executable support enabled.
Mon Jul 18 18:14:05 2016 -> ELF support enabled.
Mon Jul 18 18:14:05 2016 -> Detection of broken executables enabled.
Mon Jul 18 18:14:05 2016 -> Mail files support enabled.
Mon Jul 18 18:14:05 2016 -> OLE2 support enabled.
Mon Jul 18 18:14:05 2016 -> PDF support enabled.
Mon Jul 18 18:14:05 2016 -> SWF support enabled.
Mon Jul 18 18:14:05 2016 -> HTML support enabled.
Mon Jul 18 18:14:05 2016 -> XMLDOCS support enabled.
Mon Jul 18 18:14:05 2016 -> HWP3 support enabled.
Mon Jul 18 18:14:05 2016 -> Self checking every 600 seconds.
Mon Jul 18 18:14:07 2016 -> Pid file removed.
Mon Jul 18 18:14:07 2016 -> --- Stopped at Mon Jul 18 18:14:07 2016
Mon Jul 18 18:14:07 2016 -> Socket file removed.`

**Comment by fritzelly** [comment]
Got the same problem and none of the previous "solutions" work

**Comment by blare** [comment]
Can you see if is there something interesting in?
`tail -f /var/log/exim/panic.log*`

**Comment by fritzelly** [comment]
Same issue that everyone else was having
 
2016-07-27 13:05:16 1bSSGi-0005iF-8e malware acl condition: clamd: unable to connect to UNIX socket (/var/run/clamav/clamd.sock): No such file or directory
 
Tried all the various fixes and nothing works

**Comment by fritzelly** [comment]
Just to add, reinstalled Vesta without Clam support (since email is kinda important), everything works perfectly

**Comment by blare** [comment]
@fritzelly I have found this,

https://forums.cpanel.net/threads/exim-clamav-connecter-issues.41313/

Last comment of 1st page and last comment of 2nd page may be helpfull.

Notice that they are chowning to mail:mail instead of clam:mail

**Comment by fritzelly** [comment]
Already tried both versions of ownership as it was one of the many things suggested in the Vesta forums, didnt make any difference and not sure that is the real underlying problem
I'm happy as is, with a working email server and will get back to it again shortly

**Comment by blare** [comment]
Ok, let us know if you find some workaround!

Thanks

**Comment by LordB101** [comment]
Gents

Had the same issue, found this guide to be spot on.

https://www.adminsys.ch/2015/08/21/installing-clamav-epel-centosred-hat-7-nightmare/

**Comment by infinitnet** [comment]
Here's a fix I use as part of my customized Vesta setup script. This is a PITA on CentOS 7. Good luck!

```
# Fix ClamAV
cat > /etc/tmpfiles.d/clamav.conf << 'EOF'
d /var/run/clamav 0755 clam clam
EOF

cat > /usr/bin/fixclamd << 'EOF'
#!/bin/bash
# Simple script to create clamd run directory for socket and pid

mkdir /var/run/clamav
chown -R clam.clam /var/run/clamav

exit 0
EOF

cat > /lib/systemd/system/clamd.service << 'EOF'
[Unit]
Description = clamd scanner (clamd) daemon
After = syslog.target nss-lookup.target network.target

[Service]
Type = simple
ExecStartPre = /usr/bin/fixclamd
ExecStart = /usr/sbin/clamd -c /etc/clamd.conf --foreground=yes
Restart = on-failure
PrivateTmp = true

[Install]
WantedBy=multi-user.target
EOF

chmod +x /usr/bin/fixclamd

systemctl daemon-reload
systemctl restart clamd
```

**Comment by dpeca** [comment]
It's fixed in v17 - https://github.com/serghey-rodin/vesta/commit/f294dc1b2a79aee37f398735fd1836561734a605

**Comment by dpeca** [comment]
From log you provided it's clearly that clamav successfully wrote pid and sock file, so there is no problem with permissions.
Something other is happening there.
Try to start clamav and provide error log here.

**Comment by lukapaunovic** [comment]
```
Fri Nov 10 13:58:53 2017 -> +++ Started at Fri Nov 10 13:58:53 2017
Fri Nov 10 13:58:53 2017 -> Received 0 file descriptor(s) from systemd.
Fri Nov 10 13:58:53 2017 -> clamd daemon 0.99.2 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Fri Nov 10 13:58:53 2017 -> Running as user clam (UID 1001, GID 1001)
Fri Nov 10 13:58:53 2017 -> Log file size limited to 4294967295 bytes.
Fri Nov 10 13:58:53 2017 -> Reading databases from /var/lib/clamav
Fri Nov 10 13:58:53 2017 -> Not loading PUA signatures.
Fri Nov 10 13:58:53 2017 -> Bytecode: Security mode set to "TrustSigned".
```


This is from email

`451 Temporary local problem - please try later`

**Comment by lukapaunovic** [comment]
Will disabling **AntiVirus Support** in mail settings fix this?

**Comment by dpeca** [comment]
Try  to reboot server?

**Comment by lukapaunovic** [comment]
Of course I did, multiple times. 

I think this fix works:

Replace 
**malware = ***  with **malware = */defer_ok**
in

`vi /etc/exim/exim.conf`

No error so far. I'm gonna let u know

**Comment by dpeca** [comment]
But it will probably just ignore connection issue to clamav....

**Comment by lukapaunovic** [comment]
I do not care about ClamAV i  care about mail sending, which still doesn't work... with this 'ignoring' i no longer get:

Error while sending the message. The mail server answered: Temporary local problem - please try later

but mail doesn't send even says it does.

**Comment by dpeca** [comment]
Maybe it goes to spam?
Try to run:
`exim -qff`

**Comment by lukapaunovic** [comment]
Mail doesn't bounce. It works. i forgot to restart exim. 

So you think this fix just ignores the issue but it seems to fixes for me, it doesn't interrupt mail sending now.

**Comment by dpeca** [comment]
I think somebody already suggested this fix, I will put in my TODO list to check suggested fix, thank you :)

**Comment by lukapaunovic** [comment]
Happened again
`2017-11-10 14:50:20 1eDAdI-0000gN-C1 malware acl condition: clamd /var/run/clamav/clamd.sock : unable to connect to UNIX socket (/var/run/clamav/clamd.sock): Connection refused`

i'm gonna try this

сhown -R clam:mail /var/run/clamav/

**Comment by dpeca** [comment]
restart clamav after it.

**Comment by lukapaunovic** [comment]
Of course.
Happened again, so this fixes are not fixing :dagger:

**Comment by dpeca** [comment]
Try to disable Antivirus for that domain.

**Comment by lukapaunovic** [comment]
I did that hours ago

**Comment by dpeca** [comment]
And it didn't solve problem?

**Comment by lukapaunovic** [comment]
obviously.
Can i remove ClamAV completely?

**Comment by lukapaunovic** [comment]
If I set CLAMD to NO in exim conf will that solve issue?

**Comment by dpeca** [comment]
Should resolve.
Restart Exim.

**Comment by lukapaunovic** [comment]
I hope so, Client is sending newsletters to subscribers that's why this is such big trouble.

**Comment by lukapaunovic** [comment]
I really believed this would solve the issue.
I have disabled clamd, chkconfig clamd off too 
I have disabled it in antivirus, i have disabled it in EXIM!

And after a reboot and empty panic.log i get this again:

 malware acl condition: clamd /var/run/clamav/clamd.sock : unable to connect to UNIX socket (/var/run/clamav/clamd.sock): No such file or direct
ory


How is this even possible?

**Comment by dpeca** [comment]
Put # before CLAMD =
and restart Exim.

**Comment by lukapaunovic** [comment]
https://pastebin.com/ybki36Xa

I already commented out everything

**Comment by dpeca** [comment]
Maybe you edit wrong conf file?

Is there any similar file in /etc/exim/ ?

You did `service exim restart` ?

**Comment by lukapaunovic** [comment]
Of course, I edited the right file, the same file web editor edits.
The changes weren't accepted because instead of NO it should be set false or 0

**Comment by dpeca** [comment]
But you anyway put # for all clamav acl rules, and Exim again had clamav acl rules... it's just impossible.
Did you solved a problem with false or 0 value?

**Comment by tuongpgjz** [comment]
Solution helps me a lot! Thank you!
