### ISSUE TITLE
Don't send emails from web mail

### ISSUE THREAD

**Issue by JhoanGamarra** [serghey-rodin/vesta#651]
try to send emails to hotmail.com or gmail , reject the message maybe beacuse has a bad configuration, and when you enter in a webmail , show much warnings , some as "file miss......" 
I have a problem with Roundcube, when I try to access to webmail, show the error: DATABASE ERROR: CONNECTION FAILED!  , try to send emails to hotmail.com or gmail , reject the message maybe beacuse has a bad configuration, and when you enter in a webmail , show much warnings , some as "file miss......" 

fresh install with ubuntu 14.4 , cent os , ubunut 15.0

**Comment by SysVoid** [comment]
Can you actually show us the errors? Screenshots or whatever. "file miss......" isn't really helpful.

**Comment by SysVoid** [comment]
Also, what version of CentOS? 6? 7?

**Comment by n1trux** [comment]
I had that problem too. It seems that some JS file didn't get included in the download by vestacp. You have to locate the missing JS file in the archive downloaded from roundcube.net and put it in `/usr/share/roundcube`.

**Comment by orwah** [comment]
it's tinymce js files .
download from :
http://sourceforge.net/projects/roundcubemail/files/roundcubemail/1.1.1/roundcubemail-1.1.1-complete.tar.gz/download

and copy
 \roundcubemail-1.1.1\program\js\tinymce\
to :
/usr/share/roundcube/program/js/tinymce/

**Comment by orwah** [comment]
https://forum.vestacp.com/viewtopic.php?f=12&t=10252

**Comment by n1trux** [comment]
This is a bug in the TinyMCE package being outdated and not with vestacp. At least on Debian, there's already an upstream bug report, which I just "refreshed" by telling the maintainer the new version would also be beneficial to roundcube.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742832

You should only copy the `tinymce.min.js` file from TinyMCE into `/usr/share/tinymce/www/`, since copying the whole editor over might break some older packages. You could also just do the following:

    ln -s /usr/share/tinymce/www/tiny_mce.js /usr/share/tinymce/www/tinymce.min.js

**Comment by SysVoid** [comment]
Closing issue since there hasn't been activity since this time last year. Assuming it's resolved.
