### ISSUE TITLE
Close github issues

### ISSUE THREAD

**Issue by n1trux** [serghey-rodin/vesta#669]
I see that the preferred way of tracking bugs is http://bugs.vestacp.com/ – so please close Github issues.

**Comment by sman591** [comment]
:+1: I personally love GitHub issues because it ties in fantastically with pull requests and the open source community, but if https://bugs.vestacp.com is the appropriate tracker, github issues shouldn't be enabled

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com - is official bug tracker of VestaCP project

**Comment by n1trux** [comment]
Yes, that is what I said.

**Comment by Satanity** [comment]
registration does not work bugs.vestacp.com

**Comment by anton-reutov** [comment]
registration working fine. You should activate your account via email

**Comment by Satanity** [comment]
i dont get the mail to activate

**Comment by anton-reutov** [comment]
You account has been activated by administrator

**Comment by Satanity** [comment]
thank u!

**Comment by n1trux** [comment]
now, er, can you disable Github Issues?

**Comment by chipitsine** [comment]
most probably, nobody care of github, can you please open a ticket at http://bugs.vestacp.com/  ?

**Comment by anton-reutov** [comment]
GitHub issues will be closed at the end of development version 0.9.8-16
https://bugs.vestacp.com/issues/199

**Comment by SysVoid** [comment]
Personally I prefer GH Issues. It's generally more secure and reliable than a 3rd party.

**Comment by n1trux** [comment]
Me too, but if the developers don't want to use github Issues and therefore don't use them at all, I'd much prefer them to link to the official bug tracker instead of just ignoring the github Issues ;)

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/ is official bug tracking system of VestaCP project
All ideas and bugs we take only from the bug tracker

**Comment by n1trux** [comment]
@anton-reutov we know that, so disable Github Issues already:

https://help.github.com/articles/disabling-issues/

**Comment by SysVoid** [comment]
@n1trux I am working my way through the old ones, closing them one by one.

If Vesta ends up closing issues completely, then I will no longer participate in the project. I won't be signing up to a 3rd party in order to track issues.

**Comment by serghey-rodin** [comment]
@n1trux thanks for help! please email me skid at vestacp.com 

@SysVoid since we have more devs involved in the project  we decided to not close github issues. At least for a while. It is definitely handy tool for developers. However it seems like are underestimating bugs.vestacp.com. The advantage is that we can form desired bug reports. We can ask submitters to specify every single detail we need like distro, architecture and so on. Actually bug.vestacp.com it is much more powerful tool.  So let's find out the best way to use both systems.

**Comment by sman591** [comment]
@serghey-rodin FWIW, you can create [contribution guidelines and GitHub issue and pull request templates](https://help.github.com/articles/helping-people-contribute-to-your-project/), which would help the need for structured bug reports, pull request details, etc. Regardless of which system is used, I'm sure there could be some use out of it

**Comment by SysVoid** [comment]
@serghey-rodin I think what @sman591 mentioned is really helpful.

We can make PR templates, and close any issues that don't conform to the template. That way all issues from the time we start that are in the same format and contain all information needed to resolve.

Also, I think we should make better use of GitHub Labels, since that will help us categorise the issues.

**Comment by anton-reutov** [comment]
bugs.vestacp.com is official bug tracking system of our project and we will continue to work with him
SysVoid you can continue to work with github issues
I think this issue should be closed

**Comment by serghey-rodin** [comment]
@sman591 I was trying to find something like that but ended up configuring labels. Thanks! It is exactly what I was looking for.

@SysVoid can you please take a look https://help.github.com/articles/creating-an-issue-template-for-your-repository/ and make template for our GH Issuses?

**Comment by SysVoid** [comment]
@serghey-rodin definitely.

**Comment by SysVoid** [comment]
All done.

**Comment by skurudo** [comment]
Do we still need this discussion? Github issues will be live.
@SysVoid May be need to close this one?

**Comment by SysVoid** [comment]
Closing issue. Thanks for your input, everyone! May the octopus issues live!
