### ISSUE TITLE
parsing snginx.conf is error and can't backup

### ISSUE THREAD

**Issue by adthonb** [serghey-rodin/vesta#723]
Hello

After I update to R16, I can't run cronjob of v-backup-users. In Vestacp control panel shows 1 backup file but no backup file. I use force-https as nginx template that it can't parse snginx.conf

![no-backup](https://cloud.githubusercontent.com/assets/18661601/16494720/88b5eb18-3f14-11e6-9304-e5bab0fee024.jpg)

I got a lot of tmp.xxxxx in /backup folder.

> /backup$ ls
> admin.log       tmp.C1CDsGij9C  tmp.HQGbRh1NMV  tmp.NoHz4NMND5  tmp.UdIawf3sRg
> ...

Here error from backup.log

> -- WEB --
> 2016-06-30 21:45:01 mydomain.com
> Error: can't parse config /home/admin/conf/web/snginx.conf

I had been reinstall Vestacp but still same.

**Comment by scorp13** [comment]
Have same issue, but with nginx.conf

Error: can't parse config /home/admin/conf/web/nginx.conf

**Comment by adthonb** [comment]
I give Serghey server access for find this issue but don't get any detail until now.

**Comment by MrGreenStuff** [comment]
Up ! Same issue closed (https://github.com/serghey-rodin/vesta/issues/719) but the problem still exist :)

**Comment by adthonb** [comment]
Update: I know cause of this issue. 
In my vesta cp I set Aliases with www.mydomain.com but in snginx.conf I change server_name variable from:
> server_name mydomain.com www.mydomain.com

to: 

> server_name mydomain.com

and v-backup-users script can't parsing config file. 
Please check this and update. previous version don't give this issue.

**Comment by mehargags** [comment]
I am having exactly the same issue as @adthonb,

My Backups were working fine until now, but a few days back I added a new Sub-Domain which I "forced" ssl only.  Since this is a subdomain I did not need a "www." alias for it so I deleted it from my (s)nginx.conf

In nginx.conf
```
server_name new.domain.com;
return      301 https://$server_name$request_uri;
```

In snginx.conf
`server_name new.domain.com;`

nginx -t shows no errors
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

After this subdomains was created, I noticed the backups stopped working. The **Backup.log** showed and error after the subdomain's line

```
2016-08-13 15:09:21 new.domain.com
Error: can't parse config /home/admin/conf/web/nginx.conf.
```

I saw this thread and added "www." alias to this subdomain in nginx & snginx conf files and the backup completed successfully in less than a minute!!

So... this is definitely a bug in the script somewhere that checks for www alias and throws error loop if not found... which needs an immediate fix. Requesting all brilliant coders of VestaCP to look upon it.

**Comment by 001101** [comment]
Having the same issue, it really sucks, takes over a month until I figured it out and find this solution.

Please remove www. checking, it is deprecated.

**Comment by anton-reutov** [comment]
Write the points of how we can reproduce the problem. One of our users said that problem still exits in v17
https://bugs.vestacp.com/issues/352

**Comment by adthonb** [comment]
@anton-reutov 
1.open snginx.conf or nginx.conf of your website in /home/$user/conf/web
2.remove www. from server_name line and save it
3.try to run v-backup-users
4.error !

**Comment by anton-reutov** [comment]
Thank you! I will check this issue

**Comment by 001101** [comment]
right! as I said months before, issue only fixable when adding www. subdomain, which is obsolete
