### ISSUE TITLE
v-rebuild-web-domains

### ISSUE THREAD

**Issue by ibrahimuslu** [serghey-rodin/vesta#813]
REbuild web domains delete all configuration and nothing write again. This is make my weekend a nightmare for me. 

Due to my configuration, there is no web_backend config variable and there is no option to rebuild in this circumstances in your code. 

Please add some code for those who make configuration without php-fpm.

**Comment by sltmunky69** [comment]
I'm not sure why this has been closed and also why this is listed as a feature request rather than a bug, because the lack of the $WEB_BACKEND variable (on Ubuntu at least) completely prevents users from being able to select or change the web template for a website and it generates the error message "[template name] web template doesn't exist". I also noticed that the way it is coded, if a template exists but not both the .tpl and .stpl files for a template, as is the case when creating a force-https template (there's no .stpl necessary), then you will also receive this message, which isn't the end of the world, but if you don't know you need both to make it work, you'll be left scratching your head as I was. The v-change-web-domain-tpl script is also affected by this.

In func/domain.sh, these minimal changes would fix:
`# Web template check
is_web_template_valid() {
    if [ ! -z "$WEB_SYSTEM" ]; then
        if [ ! -z "$WEB_BACKEND" ]; then
            tpl="$WEBTPL/$WEB_SYSTEM/$WEB_BACKEND/$1.tpl"
            stpl="$WEBTPL/$WEB_SYSTEM/$WEB_BACKEND/$1.stpl"
        else
            tpl="$WEBTPL/$WEB_SYSTEM/$1.tpl"
            stpl="$WEBTPL/$WEB_SYSTEM/$1.stpl"
        fi
        if [ ! -e "$tpl" ] || [ ! -e "$stpl" ]; then
            check_result $E_NOTEXIST "$1 web template doesn't exist"
        fi
    fi
}
`
