### ISSUE TITLE
v-add-sys-quota  unterminated `s' command error when running script

### ISSUE THREAD

**Issue by JoshIdeas** [serghey-rodin/vesta#844]
### Operating System (OS/VERSION):

Ubuntu 14.04LTS
### VestaCP Version:

Vesta 0.9.8-16
### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql
### Steps to Reproduce:

run v-add-sys-quota
### Related Issues/Forum Threads:

Nothing found related

Vesta 0.9.8-16

When the v-add-sys-quota is executed: 

~# v-add-sys-quota
sed: -e expression #1, char 11: unterminated `s' command
quotaoff: Mountpoint (or device) / not found or has no quota enabled.

**Comment by Skamasle** [comment]
The problem comes because script read coments.

For example, one of my default /etc/fstab when I get same error:

`# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda1 during installation
UUID=f9dcfdb1-5c18-40ba-a9df-d76c4a54e1f9 /               btrfs   defaults        0       1
# swap was on /dev/sda5 during installation
UUID=67ccbd35-2dd6-4fd4-8353-64926bdc7315 none            swap    sw              0       0
`
Here I get same error

sed: -e expression #1, char 11: unterminated `s' command`

I remove one coment and all working fine

```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
UUID=f9dcfdb1-5c18-40ba-a9df-d76c4a54e1f9 /               btrfs   defaults        0       1
# swap was on /dev/sda5 during installation
UUID=67ccbd35-2dd6-4fd4-8353-64926bdc7315 none            swap    sw              0       0
```





`
