### ISSUE TITLE
nginx service not starting on fresh install

### ISSUE THREAD

**Issue by apachler** [serghey-rodin/vesta#846]
### Operating System (OS/VERSION):

CentOS 7
### VestaCP Version:

0.9.8-16
### Other Notes:

It is not possible to install VestaCP at all because there is a problem with the PID file of nginx. The nginx.conf specifies it at /var/run/nginx.pid but the systemd service is awaiting it at /run/nginx.conf.

**Comment by anton-reutov** [comment]
Hi, I want to check this problem on your server
Please, send me access to your server via our forum https://forum.vestacp.com/ my nickname imperio

**Comment by apachler** [comment]
I can not give you access to my server, sorry. Please let me know what information you need and i am going to provide it.
Thanks

**Comment by anton-reutov** [comment]
I'm should testing this problem on your server or server where this problem is reproducible, if you don't want to sending credentials i cant to check this error

**Comment by apachler** [comment]
I just installed a fresh CentOS Linux release 7.2.1511 (Core)

And after that i have installed VestCP with:
bash vst-install.sh --nginx yes --apache yes --phpfpm no --vsftpd yes --proftpd no --exim no --dovecot no --spamassassin no --clamav no --named no --iptables no --fail2ban no --mysql yes --postgresql no --remi yes --quota no

The install script tried to restart nginx and was not able to do so. The installation aborted.

I manually tried to start nginx and systemd told me that it is waiting for nginx to start properly. Systemd aborted because nop PID file were created. So i just jumped in a looked at the systemd
service script of nginx and saw that the service is awaiting the nginx PID file at /run/nginx.pid.

Next step was to see where nginx is writing its PID file. Like defined in /etc/nginx/nginx.conf the
PID file is created at "pid                     /var/run/nginx.pid;". This can not work ;)

So i just have changed the config setting of nginx to "pid                     /run/nginx.pid;" and everything works like expected.

Therefore i needed to change the vestacp install script so that it dont overwrite my changed nginx config and i was able to restart the installation with the --force flag.

**Comment by huloza** [comment]
Confirmed two times in CentOS 7 fresh intall, nginx not starting.

**Comment by Skamasle** [comment]
I cant reproduce this.

I just install vesta today:

cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

nginx.service - nginx - high performance web server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: active (running) since vie 2016-09-30 17:30:51 UTC; 9s ago
     Docs: http://nginx.org/en/docs/
  Process: 32659 ExecStop=/bin/kill -s QUIT $MAINPID (code=exited, status=0/SUCCESS)
  Process: 32665 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)
  Process: 32664 ExecStartPre=/usr/sbin/nginx -t -c /etc/nginx/nginx.conf (code=exited, status=0/SUCCESS)
 Main PID: 32667 (nginx)

Nginx working fine, restart whitout any problems
