### ISSUE TITLE
Auth log does not contain date and time

### ISSUE THREAD

**Issue by philip-sorokin** [serghey-rodin/vesta#857]
Issue related to a closed PR [https://github.com/serghey-rodin/vesta/pull/854](https://github.com/serghey-rodin/vesta/pull/854)

Vesta auth log (as well as the other logs, I suppose) does not contain date and time, because the date and time variables are missing in the `main.sh` script (see the PR).

**Comment by dpeca** [comment]
It fixed in github version, I just checked - http://mycity.tech/screenshots/logs.png

But anyway, logs are still broken if log contains double-quote characters.
I'll open another issue for that.

This issue can be closed.

**Comment by philip-sorokin** [comment]
@dpeca, did you open a file `/var/log/vesta/auth.log`?

**Comment by dpeca** [comment]
`  admin 176.67.218.** successfully logged in
2016-10-05 13:55:12 admin 109.92.137.** successfully logged in
2016-10-06 21:11:48 admin 178.149.201.*** successfully logged in
2016-10-07 09:41:07 admin 178.149.201.*** successfully logged in`

As you can  see, first line is without time, because it's a source code from Vesta installation.
But after fetching new versions of source code from github, time is logged.

**Comment by philip-sorokin** [comment]
OK, thanks! I am closing this one!

**Comment by philip-sorokin** [comment]
I think, you should make a new security release ASAP, because fail2ban does not work without date in logs.
