### ISSUE TITLE
Database backup failed - parameter removed for pg_dump in PostgreSQL v9.5

### ISSUE THREAD

**Issue by schnes4** [serghey-rodin/vesta#913]
### Operating System (OS/VERSION):

Each Operating System

### VestaCP Version:

Vesta 0.9.8-16

### Installed Software (what you got with the installer):

PostgreSQL v9.5

### Steps to Reproduce:

Install minimum version 9.5 of PostgreSQL (latest version is 9.6) and create a backup of admin user.
Error logs:

$VESTA/log/error.log:   
```
2016-11-17 20:05:43 v-backup-user  'admin' 'yes' [Error 17]
```

$VESTA/log/db.log:      
```
-- DB --
2016-11-17 20:05:43 admin_db (pgsql)
sh: 0: getcwd() failed: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: 0: getcwd() failed: No such file or directory
Error: dump admin_db failed
```

Error mail:

```
Can't dump database admin_db
/usr/lib/postgresql/9.5/bin/pg_dump: invalid option -- 'i'
Try "pg_dump --help" for more information.
```

### Other Notes:

The parameter -i was removed in version 9.5. I solved this Issue manually by removing the -i option in the $VESTA/func/db.sh script (line 88)

From PostgreSQL doku (v9.4):

> -i
--ignore-version
A deprecated option that is now ignored.

https://www.postgresql.org/docs/9.4/static/app-pgdump.html

**Comment by noogen** [comment]
I can confirm this is also an issue in latest version VestapCP 0.9.8-17, Ubuntu 16.04, and PSQL9.5.  Backup was stuck until I implemented the fix described above.  Thanks schnes4.

**Comment by noogen** [comment]
Did some server migration and discovered that the postgresql backup didn't restore correctly.

1) The backup script drop and recreate table (-c option).  It also does not generate correct permissions (-O option) for the tables. 
2) The restore script does not allow user to login.
3) The restore script has a casing typo (due to copy and paste from db create script).

Fix: 
sed -i -e "s/\-c \-\-inserts \-O \-x \-i \-f/\-\-inserts \-x \-f/g" /usr/local/vesta/func/db.sh \
&& sed -i -e "s/ROLE \$DBUSER/ROLE \$DBUSER WITH LOGIN/g" /usr/local/vesta/func/rebuild.sh \
&& sed -i -e "s/dbuser/DBUSER/g" /usr/local/vesta/func/rebuild.sh

Remove -c -O -i && add "WITH LOGIN" && fix casing typo

**Comment by nurul-umbhiya** [comment]
This fix worked for me too. Finally backup is successful. Thanks.
